// Banque Blind Test — la preview est cherchée via l'API Deezer (artist + title)
// cat : popfr / rapfr / popint / rapint / rock / electro / oldies
const BLINDTEST = [
  { artist: "Stromae", title: "Papaoutai", cat: "popfr" },
  { artist: "Stromae", title: "Alors on danse", cat: "popfr" },
  { artist: "Stromae", title: "Formidable", cat: "popfr" },
  { artist: "Stromae", title: "Santé", cat: "popfr" },
  { artist: "Indila", title: "Dernière danse", cat: "popfr" },
  { artist: "Angèle", title: "Balance ton quoi", cat: "popfr" },
  { artist: "Angèle", title: "Bruxelles je t'aime", cat: "popfr" },
  { artist: "Aya Nakamura", title: "Djadja", cat: "popfr" },
  { artist: "Aya Nakamura", title: "Pookie", cat: "popfr" },
  { artist: "Clara Luciani", title: "La grenade", cat: "popfr" },
  { artist: "Zaz", title: "Je veux", cat: "popfr" },
  { artist: "Louane", title: "Avenir", cat: "popfr" },
  { artist: "Louane", title: "Jour 1", cat: "popfr" },
  { artist: "Vianney", title: "Pas là", cat: "popfr" },
  { artist: "Vianney", title: "Je m'en vais", cat: "popfr" },
  { artist: "Slimane", title: "Viens on s'aime", cat: "popfr" },
  { artist: "Vitaa & Slimane", title: "Ça va ça vient", cat: "popfr" },
  { artist: "Kendji Girac", title: "Color Gitano", cat: "popfr" },
  { artist: "Kendji Girac", title: "Andalouse", cat: "popfr" },
  { artist: "M. Pokora", title: "On est là", cat: "popfr" },
  { artist: "M. Pokora", title: "Juste une photo de toi", cat: "popfr" },
  { artist: "Tal", title: "Le sens de la vie", cat: "popfr" },
  { artist: "Amel Bent", title: "Ma philosophie", cat: "popfr" },
  { artist: "Christophe Maé", title: "Il est où le bonheur", cat: "popfr" },
  { artist: "Christophe Maé", title: "On s'attache", cat: "popfr" },
  { artist: "Calogero", title: "En apesanteur", cat: "popfr" },
  { artist: "Calogero", title: "Face à la mer", cat: "popfr" },
  { artist: "Julien Doré", title: "Paris-Seychelles", cat: "popfr" },
  { artist: "Julien Doré", title: "Coco Câline", cat: "popfr" },
  { artist: "Hoshi", title: "Ta marinière", cat: "popfr" },
  { artist: "Pomme", title: "On brûlera", cat: "popfr" },
  { artist: "Alizée", title: "Moi Lolita", cat: "popfr" },
  { artist: "Jenifer", title: "Au soleil", cat: "popfr" },
  { artist: "Shy'm", title: "Femme de couleur", cat: "popfr" },
  { artist: "Claudio Capéo", title: "Un homme debout", cat: "popfr" },
  { artist: "Kyo", title: "Le chemin", cat: "popfr" },
  { artist: "Kyo", title: "Dernière danse", cat: "popfr" },
  { artist: "BB Brunes", title: "Coups et blessures", cat: "popfr" },
  { artist: "Superbus", title: "Butterfly", cat: "popfr" },
  { artist: "Cœur de Pirate", title: "Comme des enfants", cat: "popfr" },
  { artist: "Yannick Noah", title: "Aux arbres citoyens", cat: "popfr" },
  { artist: "Grégoire", title: "Toi + Moi", cat: "popfr" },
  { artist: "Cali", title: "Elle m'a dit", cat: "popfr" },
  { artist: "Mickey 3D", title: "Respire", cat: "popfr" },
  { artist: "Tryo", title: "L'hymne de nos campagnes", cat: "popfr" },
  { artist: "Wejdene", title: "Anissa", cat: "popfr" },
  { artist: "Camille Lellouche & Grand Corps Malade", title: "Mais je t'aime", cat: "popfr" },
  { artist: "Soprano", title: "Cosmo", cat: "popfr" },
  { artist: "Black M", title: "Sur ma route", cat: "popfr" },
  { artist: "Maître Gims", title: "Bella", cat: "popfr" },
  { artist: "Maître Gims", title: "J'me tire", cat: "popfr" },
  { artist: "Maître Gims", title: "Est-ce que tu m'aimes", cat: "popfr" },
  { artist: "Lilly Wood and The Prick", title: "Prayer in C", cat: "popfr" },
  { artist: "Christine and the Queens", title: "Christine", cat: "popfr" },
  { artist: "Diam's", title: "La boulette", cat: "rapfr" },
  { artist: "Diam's", title: "Jeune demoiselle", cat: "rapfr" },
  { artist: "Booba", title: "Pitbull", cat: "rapfr" },
  { artist: "Booba", title: "DKR", cat: "rapfr" },
  { artist: "PNL", title: "Au DD", cat: "rapfr" },
  { artist: "PNL", title: "Deux frères", cat: "rapfr" },
  { artist: "Orelsan", title: "La fête est finie", cat: "rapfr" },
  { artist: "Orelsan", title: "Basique", cat: "rapfr" },
  { artist: "Orelsan", title: "Tout va bien", cat: "rapfr" },
  { artist: "Nekfeu", title: "On verra", cat: "rapfr" },
  { artist: "Nekfeu", title: "Squa", cat: "rapfr" },
  { artist: "Bigflo & Oli", title: "Dommage", cat: "rapfr" },
  { artist: "Bigflo & Oli", title: "Plus tard", cat: "rapfr" },
  { artist: "Lomepal", title: "Trop beau", cat: "rapfr" },
  { artist: "Lomepal", title: "Yeux disent", cat: "rapfr" },
  { artist: "Vald", title: "Journal perso", cat: "rapfr" },
  { artist: "Damso", title: "Macarena", cat: "rapfr" },
  { artist: "Ninho", title: "Lettre à une femme", cat: "rapfr" },
  { artist: "Ninho", title: "Goutte d'eau", cat: "rapfr" },
  { artist: "Jul", title: "Tchikita", cat: "rapfr" },
  { artist: "Jul", title: "My World", cat: "rapfr" },
  { artist: "SCH", title: "Mannschaft", cat: "rapfr" },
  { artist: "Naps", title: "La kiffance", cat: "rapfr" },
  { artist: "Gazo", title: "Die", cat: "rapfr" },
  { artist: "Gazo", title: "Celine 3x", cat: "rapfr" },
  { artist: "PLK", title: "Un peu de haine", cat: "rapfr" },
  { artist: "Niska", title: "Réseaux", cat: "rapfr" },
  { artist: "Niska", title: "Salé", cat: "rapfr" },
  { artist: "MHD", title: "Afro Trap Part. 7", cat: "rapfr" },
  { artist: "Gradur", title: "Rosa", cat: "rapfr" },
  { artist: "Soolking", title: "Guérilla", cat: "rapfr" },
  { artist: "Soolking", title: "Dalida", cat: "rapfr" },
  { artist: "Heuss L'Enfoiré", title: "Khapta", cat: "rapfr" },
  { artist: "Vegedream", title: "Ramenez la coupe à la maison", cat: "rapfr" },
  { artist: "Kaaris", title: "Tchoin", cat: "rapfr" },
  { artist: "IAM", title: "Je danse le Mia", cat: "rapfr" },
  { artist: "MC Solaar", title: "Caroline", cat: "rapfr" },
  { artist: "Suprême NTM", title: "Ma Benz", cat: "rapfr" },
  { artist: "Sniper", title: "Gravé dans la roche", cat: "rapfr" },
  { artist: "Sexion d'Assaut", title: "Désolé", cat: "rapfr" },
  { artist: "Sexion d'Assaut", title: "Avant qu'elle parte", cat: "rapfr" },
  { artist: "La Fouine", title: "Ma meilleure", cat: "rapfr" },
  { artist: "Rohff", title: "Qui est l'exemple", cat: "rapfr" },
  { artist: "Kamini", title: "Marly-Gomont", cat: "rapfr" },
  { artist: "Stupeflip", title: "Stupeflip Vite !!!", cat: "rapfr" },
  { artist: "Tayc", title: "Le temps", cat: "rapfr" },
  { artist: "Dadju", title: "Reine", cat: "rapfr" },
  { artist: "Dadju", title: "Jaloux", cat: "rapfr" },
  { artist: "Franglish", title: "Position", cat: "rapfr" },
  { artist: "Ed Sheeran", title: "Shape of You", cat: "popint" },
  { artist: "Ed Sheeran", title: "Perfect", cat: "popint" },
  { artist: "Adele", title: "Rolling in the Deep", cat: "popint" },
  { artist: "Adele", title: "Hello", cat: "popint" },
  { artist: "Adele", title: "Someone Like You", cat: "popint" },
  { artist: "Taylor Swift", title: "Shake It Off", cat: "popint" },
  { artist: "Taylor Swift", title: "Anti-Hero", cat: "popint" },
  { artist: "Billie Eilish", title: "Bad Guy", cat: "popint" },
  { artist: "Harry Styles", title: "As It Was", cat: "popint" },
  { artist: "Harry Styles", title: "Watermelon Sugar", cat: "popint" },
  { artist: "Dua Lipa", title: "Levitating", cat: "popint" },
  { artist: "Dua Lipa", title: "Don't Start Now", cat: "popint" },
  { artist: "Lady Gaga", title: "Bad Romance", cat: "popint" },
  { artist: "Lady Gaga", title: "Poker Face", cat: "popint" },
  { artist: "Lady Gaga & Bruno Mars", title: "Die With A Smile", cat: "popint" },
  { artist: "Rihanna", title: "Umbrella", cat: "popint" },
  { artist: "Rihanna", title: "Diamonds", cat: "popint" },
  { artist: "Beyoncé", title: "Single Ladies", cat: "popint" },
  { artist: "Beyoncé", title: "Crazy in Love", cat: "popint" },
  { artist: "Bruno Mars", title: "Uptown Funk", cat: "popint" },
  { artist: "Bruno Mars", title: "Just the Way You Are", cat: "popint" },
  { artist: "Pharrell Williams", title: "Happy", cat: "popint" },
  { artist: "Katy Perry", title: "Roar", cat: "popint" },
  { artist: "Katy Perry", title: "Firework", cat: "popint" },
  { artist: "Maroon 5", title: "Sugar", cat: "popint" },
  { artist: "Maroon 5", title: "Moves Like Jagger", cat: "popint" },
  { artist: "Justin Bieber", title: "Sorry", cat: "popint" },
  { artist: "Justin Bieber", title: "Baby", cat: "popint" },
  { artist: "Justin Timberlake", title: "Can't Stop the Feeling!", cat: "popint" },
  { artist: "Ariana Grande", title: "7 rings", cat: "popint" },
  { artist: "Ariana Grande", title: "Thank U, Next", cat: "popint" },
  { artist: "Olivia Rodrigo", title: "drivers license", cat: "popint" },
  { artist: "Olivia Rodrigo", title: "good 4 u", cat: "popint" },
  { artist: "Doja Cat", title: "Say So", cat: "popint" },
  { artist: "Glass Animals", title: "Heat Waves", cat: "popint" },
  { artist: "Miley Cyrus", title: "Flowers", cat: "popint" },
  { artist: "Miley Cyrus", title: "Wrecking Ball", cat: "popint" },
  { artist: "Sam Smith", title: "Stay With Me", cat: "popint" },
  { artist: "Lewis Capaldi", title: "Someone You Loved", cat: "popint" },
  { artist: "Sia", title: "Chandelier", cat: "popint" },
  { artist: "Sia", title: "Cheap Thrills", cat: "popint" },
  { artist: "Lorde", title: "Royals", cat: "popint" },
  { artist: "The Weeknd", title: "Blinding Lights", cat: "popint" },
  { artist: "The Weeknd", title: "Starboy", cat: "popint" },
  { artist: "The Weeknd", title: "Save Your Tears", cat: "popint" },
  { artist: "Shakira", title: "Hips Don't Lie", cat: "popint" },
  { artist: "Shakira", title: "Waka Waka", cat: "popint" },
  { artist: "Amy Winehouse", title: "Rehab", cat: "popint" },
  { artist: "Amy Winehouse", title: "Back to Black", cat: "popint" },
  { artist: "Coldplay", title: "Viva la Vida", cat: "popint" },
  { artist: "Coldplay", title: "The Scientist", cat: "popint" },
  { artist: "Coldplay", title: "Yellow", cat: "popint" },
  { artist: "Gnarls Barkley", title: "Crazy", cat: "popint" },
  { artist: "Gorillaz", title: "Feel Good Inc.", cat: "popint" },
  { artist: "OneRepublic", title: "Counting Stars", cat: "popint" },
  { artist: "Imagine Dragons", title: "Believer", cat: "popint" },
  { artist: "Imagine Dragons", title: "Radioactive", cat: "popint" },
  { artist: "Hozier", title: "Take Me to Church", cat: "popint" },
  { artist: "Alicia Keys", title: "No One", cat: "popint" },
  { artist: "Alicia Keys", title: "Girl on Fire", cat: "popint" },
  { artist: "Black Eyed Peas", title: "I Gotta Feeling", cat: "popint" },
  { artist: "Black Eyed Peas", title: "Where Is the Love?", cat: "popint" },
  { artist: "Britney Spears", title: "Toxic", cat: "popint" },
  { artist: "Britney Spears", title: "...Baby One More Time", cat: "popint" },
  { artist: "Beyoncé", title: "Halo", cat: "popint" },
  { artist: "Rosé & Bruno Mars", title: "APT.", cat: "popint" },
  { artist: "Eminem", title: "Lose Yourself", cat: "rapint" },
  { artist: "Eminem", title: "Without Me", cat: "rapint" },
  { artist: "Eminem", title: "The Real Slim Shady", cat: "rapint" },
  { artist: "Eminem ft. Rihanna", title: "Love The Way You Lie", cat: "rapint" },
  { artist: "50 Cent", title: "In Da Club", cat: "rapint" },
  { artist: "50 Cent", title: "Candy Shop", cat: "rapint" },
  { artist: "Kanye West", title: "Stronger", cat: "rapint" },
  { artist: "Kanye West", title: "Gold Digger", cat: "rapint" },
  { artist: "Jay-Z & Alicia Keys", title: "Empire State of Mind", cat: "rapint" },
  { artist: "Kendrick Lamar", title: "HUMBLE.", cat: "rapint" },
  { artist: "Drake", title: "One Dance", cat: "rapint" },
  { artist: "Drake", title: "God's Plan", cat: "rapint" },
  { artist: "Drake", title: "Hotline Bling", cat: "rapint" },
  { artist: "Post Malone", title: "Rockstar", cat: "rapint" },
  { artist: "Post Malone & Swae Lee", title: "Sunflower", cat: "rapint" },
  { artist: "Outkast", title: "Hey Ya!", cat: "rapint" },
  { artist: "Macklemore & Ryan Lewis", title: "Thrift Shop", cat: "rapint" },
  { artist: "Macklemore & Ryan Lewis", title: "Can't Hold Us", cat: "rapint" },
  { artist: "Lil Nas X", title: "Old Town Road", cat: "rapint" },
  { artist: "Lil Nas X", title: "MONTERO (Call Me By Your Name)", cat: "rapint" },
  { artist: "Childish Gambino", title: "This Is America", cat: "rapint" },
  { artist: "Nelly", title: "Dilemma", cat: "rapint" },
  { artist: "Usher", title: "Yeah!", cat: "rapint" },
  { artist: "Snoop Dogg", title: "Drop It Like It's Hot", cat: "rapint" },
  { artist: "The Notorious B.I.G.", title: "Juicy", cat: "rapint" },
  { artist: "2Pac", title: "California Love", cat: "rapint" },
  { artist: "Dr. Dre ft. Snoop Dogg", title: "Still D.R.E.", cat: "rapint" },
  { artist: "House of Pain", title: "Jump Around", cat: "rapint" },
  { artist: "Coolio", title: "Gangsta's Paradise", cat: "rapint" },
  { artist: "Travis Scott", title: "SICKO MODE", cat: "rapint" },
  { artist: "Queen", title: "Bohemian Rhapsody", cat: "rock" },
  { artist: "Queen", title: "We Will Rock You", cat: "rock" },
  { artist: "Queen", title: "Don't Stop Me Now", cat: "rock" },
  { artist: "Nirvana", title: "Smells Like Teen Spirit", cat: "rock" },
  { artist: "Nirvana", title: "Come as You Are", cat: "rock" },
  { artist: "The Rolling Stones", title: "Paint It, Black", cat: "rock" },
  { artist: "The Rolling Stones", title: "Satisfaction", cat: "rock" },
  { artist: "The Beatles", title: "Let It Be", cat: "rock" },
  { artist: "The Beatles", title: "Hey Jude", cat: "rock" },
  { artist: "Oasis", title: "Wonderwall", cat: "rock" },
  { artist: "Oasis", title: "Don't Look Back in Anger", cat: "rock" },
  { artist: "The White Stripes", title: "Seven Nation Army", cat: "rock" },
  { artist: "Green Day", title: "Boulevard of Broken Dreams", cat: "rock" },
  { artist: "Green Day", title: "American Idiot", cat: "rock" },
  { artist: "Linkin Park", title: "In the End", cat: "rock" },
  { artist: "Linkin Park", title: "Numb", cat: "rock" },
  { artist: "Red Hot Chili Peppers", title: "Californication", cat: "rock" },
  { artist: "Red Hot Chili Peppers", title: "Under the Bridge", cat: "rock" },
  { artist: "The Killers", title: "Mr. Brightside", cat: "rock" },
  { artist: "Arctic Monkeys", title: "Do I Wanna Know?", cat: "rock" },
  { artist: "Muse", title: "Supermassive Black Hole", cat: "rock" },
  { artist: "Muse", title: "Uprising", cat: "rock" },
  { artist: "Foo Fighters", title: "Everlong", cat: "rock" },
  { artist: "Bon Jovi", title: "Livin' on a Prayer", cat: "rock" },
  { artist: "Bon Jovi", title: "It's My Life", cat: "rock" },
  { artist: "Europe", title: "The Final Countdown", cat: "rock" },
  { artist: "Survivor", title: "Eye of the Tiger", cat: "rock" },
  { artist: "Journey", title: "Don't Stop Believin'", cat: "rock" },
  { artist: "Téléphone", title: "Ça (c'est vraiment toi)", cat: "rock" },
  { artist: "Téléphone", title: "New York avec toi", cat: "rock" },
  { artist: "Noir Désir", title: "Le vent nous portera", cat: "rock" },
  { artist: "Indochine", title: "L'Aventurier", cat: "rock" },
  { artist: "Indochine", title: "J'ai demandé à la lune", cat: "rock" },
  { artist: "Johnny Hallyday", title: "Allumer le feu", cat: "rock" },
  { artist: "Louise Attaque", title: "J't'emmène au vent", cat: "rock" },
  { artist: "Daft Punk", title: "One More Time", cat: "electro" },
  { artist: "Daft Punk", title: "Get Lucky", cat: "electro" },
  { artist: "Daft Punk", title: "Around the World", cat: "electro" },
  { artist: "Daft Punk", title: "Harder Better Faster Stronger", cat: "electro" },
  { artist: "David Guetta ft. Sia", title: "Titanium", cat: "electro" },
  { artist: "David Guetta", title: "When Love Takes Over", cat: "electro" },
  { artist: "Avicii", title: "Wake Me Up", cat: "electro" },
  { artist: "Avicii", title: "Levels", cat: "electro" },
  { artist: "Martin Solveig", title: "Hello", cat: "electro" },
  { artist: "Calvin Harris", title: "Summer", cat: "electro" },
  { artist: "Calvin Harris & Rihanna", title: "This Is What You Came For", cat: "electro" },
  { artist: "The Chainsmokers", title: "Closer", cat: "electro" },
  { artist: "Kavinsky", title: "Nightcall", cat: "electro" },
  { artist: "Petit Biscuit", title: "Sunset Lover", cat: "electro" },
  { artist: "Polo & Pan", title: "Canopée", cat: "electro" },
  { artist: "L'Impératrice", title: "Peur des filles", cat: "electro" },
  { artist: "Stardust", title: "Music Sounds Better with You", cat: "electro" },
  { artist: "Modjo", title: "Lady (Hear Me Tonight)", cat: "electro" },
  { artist: "Bob Sinclar", title: "Love Generation", cat: "electro" },
  { artist: "Yolanda Be Cool & DCUP", title: "We No Speak Americano", cat: "electro" },
  { artist: "Swedish House Mafia", title: "Don't You Worry Child", cat: "electro" },
  { artist: "Major Lazer", title: "Lean On", cat: "electro" },
  { artist: "Marshmello ft. Bastille", title: "Happier", cat: "electro" },
  { artist: "Alan Walker", title: "Faded", cat: "electro" },
  { artist: "Michael Jackson", title: "Billie Jean", cat: "oldies" },
  { artist: "Michael Jackson", title: "Thriller", cat: "oldies" },
  { artist: "Michael Jackson", title: "Beat It", cat: "oldies" },
  { artist: "ABBA", title: "Dancing Queen", cat: "oldies" },
  { artist: "ABBA", title: "Gimme! Gimme! Gimme!", cat: "oldies" },
  { artist: "a-ha", title: "Take On Me", cat: "oldies" },
  { artist: "Toto", title: "Africa", cat: "oldies" },
  { artist: "Madonna", title: "Like a Prayer", cat: "oldies" },
  { artist: "Madonna", title: "La Isla Bonita", cat: "oldies" },
  { artist: "Cyndi Lauper", title: "Girls Just Want to Have Fun", cat: "oldies" },
  { artist: "Whitney Houston", title: "I Will Always Love You", cat: "oldies" },
  { artist: "Whitney Houston", title: "I Wanna Dance with Somebody", cat: "oldies" },
  { artist: "George Michael", title: "Careless Whisper", cat: "oldies" },
  { artist: "Wham!", title: "Last Christmas", cat: "oldies" },
  { artist: "Spice Girls", title: "Wannabe", cat: "oldies" },
  { artist: "Backstreet Boys", title: "I Want It That Way", cat: "oldies" },
  { artist: "Aqua", title: "Barbie Girl", cat: "oldies" },
  { artist: "Céline Dion", title: "My Heart Will Go On", cat: "oldies" },
  { artist: "Céline Dion", title: "Pour que tu m'aimes encore", cat: "oldies" },
  { artist: "Elton John", title: "I'm Still Standing", cat: "oldies" },
  { artist: "Depeche Mode", title: "Enjoy the Silence", cat: "oldies" },
  { artist: "The Police", title: "Every Breath You Take", cat: "oldies" },
  { artist: "Édith Piaf", title: "Non, je ne regrette rien", cat: "oldies" },
  { artist: "Édith Piaf", title: "La Vie en rose", cat: "oldies" },
  { artist: "Jacques Brel", title: "Ne me quitte pas", cat: "oldies" },
  { artist: "Claude François", title: "Alexandrie Alexandra", cat: "oldies" },
  { artist: "Claude François", title: "Cette année-là", cat: "oldies" },
  { artist: "Michel Sardou", title: "Les lacs du Connemara", cat: "oldies" },
  { artist: "Michel Sardou", title: "La maladie d'amour", cat: "oldies" },
  { artist: "France Gall", title: "Ella, elle l'a", cat: "oldies" },
  { artist: "France Gall", title: "Résiste", cat: "oldies" },
  { artist: "Michel Berger", title: "Quelque chose de Tennessee", cat: "oldies" },
  { artist: "Daniel Balavoine", title: "L'Aziza", cat: "oldies" },
  { artist: "Jean-Jacques Goldman", title: "Je te donne", cat: "oldies" },
  { artist: "Jean-Jacques Goldman", title: "Quand la musique est bonne", cat: "oldies" },
  { artist: "Renaud", title: "Mistral gagnant", cat: "oldies" },
  { artist: "Francis Cabrel", title: "Je l'aime à mourir", cat: "oldies" },
  { artist: "Serge Gainsbourg", title: "Je t'aime moi non plus", cat: "oldies" },
  { artist: "Mylène Farmer", title: "Désenchantée", cat: "oldies" },
  { artist: "Mylène Farmer", title: "Sans contrefaçon", cat: "oldies" },
  { artist: "Patrick Bruel", title: "Casser la voix", cat: "oldies" },
  { artist: "Les Rita Mitsouko", title: "Marcia Baïla", cat: "oldies" },
  { artist: "Desireless", title: "Voyage voyage", cat: "oldies" },
  { artist: "Partenaire Particulier", title: "Partenaire particulier", cat: "oldies" },
  { artist: "Boney M.", title: "Rasputin", cat: "oldies" },
  { artist: "Bee Gees", title: "Stayin' Alive", cat: "oldies" },
  { artist: "Earth, Wind & Fire", title: "September", cat: "oldies" },
  { artist: "Village People", title: "Y.M.C.A.", cat: "oldies" },
  { artist: "Gloria Gaynor", title: "I Will Survive", cat: "oldies" },
  { artist: "Elvis Presley", title: "Suspicious Minds", cat: "oldies" },
  { artist: "Céphaz", title: "On a mangé le soleil", cat: "popfr" },
  { artist: "Gims & Vitaa", title: "Prends ma main", cat: "popfr" },
  { artist: "Amir", title: "J'ai cherché", cat: "popfr" },
  { artist: "Amir", title: "Longtemps", cat: "popfr" },
  { artist: "Kendji Girac & Soprano", title: "No me mirès màs", cat: "popfr" },
  { artist: "Patrick Fiori", title: "4 mots sur un piano", cat: "popfr" },
  { artist: "Zazie", title: "Zen", cat: "popfr" },
  { artist: "Pascal Obispo", title: "Lucie", cat: "popfr" },
  { artist: "Florent Pagny", title: "Savoir aimer", cat: "popfr" },
  { artist: "Florent Pagny", title: "Ma liberté de penser", cat: "popfr" },
  { artist: "Garou", title: "Seul", cat: "popfr" },
  { artist: "Hélène Ségara", title: "Il y a trop de gens qui t'aiment", cat: "popfr" },
  { artist: "Lara Fabian", title: "Je t'aime", cat: "popfr" },
  { artist: "Nolwenn Leroy", title: "Cassé", cat: "popfr" },
  { artist: "Christophe Willem", title: "Double je", cat: "popfr" },
  { artist: "Emmanuel Moire", title: "Beau malheur", cat: "popfr" },
  { artist: "Fréro Delavega", title: "Le chant des sirènes", cat: "popfr" },
  { artist: "Fréro Delavega", title: "Sweet Darling", cat: "popfr" },
  { artist: "Boulevard des Airs", title: "Emmène-moi", cat: "popfr" },
  { artist: "Trois Cafés Gourmands", title: "À nos souvenirs", cat: "popfr" },
  { artist: "Ben Mazué", title: "Vivant", cat: "popfr" },
  { artist: "Grand Corps Malade", title: "Mesdames", cat: "popfr" },
  { artist: "Barbara Pravi", title: "Voilà", cat: "popfr" },
  { artist: "Juliette Armanet", title: "Le dernier jour du disco", cat: "popfr" },
  { artist: "Eddy de Pretto", title: "Fête de trop", cat: "popfr" },
  { artist: "Pierre de Maere", title: "Un jour je marierai un ange", cat: "popfr" },
  { artist: "Santa", title: "Popcorn salé", cat: "popfr" },
  { artist: "Zaho de Sagazan", title: "La symphonie des éclairs", cat: "popfr" },
  { artist: "Louane", title: "Donne-moi ton cœur", cat: "popfr" },
  { artist: "Keen'V", title: "Rien qu'une fois", cat: "popfr" },
  { artist: "Magic System", title: "Magic in the Air", cat: "popfr" },
  { artist: "Magic System", title: "Premier Gaou", cat: "popfr" },
  { artist: "Collectif Métissé", title: "Laisse tomber tes problèmes", cat: "popfr" },
  { artist: "Shakira & Freshlyground", title: "Waka Waka (This Time for Africa)", cat: "popint" },
  { artist: "Zaz", title: "On ira", cat: "popfr" },
  { artist: "Timal", title: "Filtré", cat: "rapfr" },
  { artist: "Gambi", title: "Popopop", cat: "rapfr" },
  { artist: "Gambi", title: "Hé oh", cat: "rapfr" },
  { artist: "Bosh", title: "Djomb", cat: "rapfr" },
  { artist: "Hatik", title: "Angela", cat: "rapfr" },
  { artist: "Josman", title: "M.E.L.O.", cat: "rapfr" },
  { artist: "Zola", title: "Papers", cat: "rapfr" },
  { artist: "Koba LaD", title: "RR 9.1", cat: "rapfr" },
  { artist: "Leto", title: "Mapessa", cat: "rapfr" },
  { artist: "Tiakola", title: "Gasolina", cat: "rapfr" },
  { artist: "Hamza", title: "Fade Up", cat: "rapfr" },
  { artist: "Laylow", title: "Special", cat: "rapfr" },
  { artist: "Alonzo", title: "Papa allô", cat: "rapfr" },
  { artist: "Alonzo", title: "La belle vie", cat: "rapfr" },
  { artist: "Naza", title: "MMM", cat: "rapfr" },
  { artist: "KeBlack", title: "Bazardée", cat: "rapfr" },
  { artist: "Dosseh", title: "Habitué", cat: "rapfr" },
  { artist: "Landy", title: "Medusa", cat: "rapfr" },
  { artist: "Guy2Bezbar", title: "Coco", cat: "rapfr" },
  { artist: "Werenoi", title: "Guadalajara", cat: "rapfr" },
  { artist: "SDM", title: "Bolide allemand", cat: "rapfr" },
  { artist: "Favé", title: "Mood", cat: "rapfr" },
  { artist: "Rim'K", title: "Air Max", cat: "rapfr" },
  { artist: "113", title: "Tonton du bled", cat: "rapfr" },
  { artist: "Lorenzo", title: "Le son qui fait plaisir", cat: "rapfr" },
  { artist: "Vald", title: "Désaccordé", cat: "rapfr" },
  { artist: "Columbine", title: "Enfants terribles", cat: "rapfr" },
  { artist: "Nekfeu ft. Vanessa Paradis", title: "Dans l'univers", cat: "rapfr" },
  { artist: "Fianso", title: "Toka", cat: "rapfr" },
  { artist: "Kalash Criminel", title: "Cougar Gang", cat: "rapfr" },
  { artist: "Sabrina Carpenter", title: "Espresso", cat: "popint" },
  { artist: "Benson Boone", title: "Beautiful Things", cat: "popint" },
  { artist: "Teddy Swims", title: "Lose Control", cat: "popint" },
  { artist: "Noah Kahan", title: "Stick Season", cat: "popint" },
  { artist: "Tate McRae", title: "Greedy", cat: "popint" },
  { artist: "Billie Eilish", title: "Birds of a Feather", cat: "popint" },
  { artist: "Billie Eilish", title: "Lovely", cat: "popint" },
  { artist: "Tones and I", title: "Dance Monkey", cat: "popint" },
  { artist: "Ed Sheeran", title: "Bad Habits", cat: "popint" },
  { artist: "Ed Sheeran", title: "Thinking Out Loud", cat: "popint" },
  { artist: "Adele", title: "Easy on Me", cat: "popint" },
  { artist: "Adele", title: "Set Fire to the Rain", cat: "popint" },
  { artist: "Camila Cabello", title: "Havana", cat: "popint" },
  { artist: "Luis Fonsi ft. Daddy Yankee", title: "Despacito", cat: "popint" },
  { artist: "Enrique Iglesias", title: "Bailando", cat: "popint" },
  { artist: "Justin Timberlake", title: "Cry Me a River", cat: "popint" },
  { artist: "Justin Timberlake", title: "SexyBack", cat: "popint" },
  { artist: "Nelly Furtado", title: "Say It Right", cat: "popint" },
  { artist: "Nelly Furtado", title: "Maneater", cat: "popint" },
  { artist: "James Blunt", title: "You're Beautiful", cat: "popint" },
  { artist: "James Arthur", title: "Say You Won't Let Go", cat: "popint" },
  { artist: "John Legend", title: "All of Me", cat: "popint" },
  { artist: "Passenger", title: "Let Her Go", cat: "popint" },
  { artist: "Wiz Khalifa ft. Charlie Puth", title: "See You Again", cat: "popint" },
  { artist: "Charlie Puth", title: "Attention", cat: "popint" },
  { artist: "Shawn Mendes", title: "There's Nothing Holdin' Me Back", cat: "popint" },
  { artist: "Shawn Mendes & Camila Cabello", title: "Señorita", cat: "popint" },
  { artist: "Zayn ft. Sia", title: "Dusk Till Dawn", cat: "popint" },
  { artist: "Clean Bandit ft. Zara Larsson", title: "Symphony", cat: "popint" },
  { artist: "Rag'n'Bone Man", title: "Human", cat: "popint" },
  { artist: "Alicia Keys", title: "If I Ain't Got You", cat: "popint" },
  { artist: "Beyoncé", title: "Texas Hold 'Em", cat: "popint" },
  { artist: "P!nk", title: "So What", cat: "popint" },
  { artist: "P!nk", title: "Just Give Me a Reason", cat: "popint" },
  { artist: "Kelly Clarkson", title: "Since U Been Gone", cat: "popint" },
  { artist: "Christina Aguilera", title: "Beautiful", cat: "popint" },
  { artist: "Jason Derulo", title: "Savage Love", cat: "popint" },
  { artist: "Jason Derulo", title: "Wiggle", cat: "popint" },
  { artist: "Meghan Trainor", title: "All About That Bass", cat: "popint" },
  { artist: "Mark Ronson ft. Miley Cyrus", title: "Nothing Breaks Like a Heart", cat: "popint" },
  { artist: "Harry Styles", title: "Sign of the Times", cat: "popint" },
  { artist: "Eminem", title: "Mockingbird", cat: "rapint" },
  { artist: "Eminem ft. Dido", title: "Stan", cat: "rapint" },
  { artist: "Eminem", title: "Godzilla", cat: "rapint" },
  { artist: "Kendrick Lamar", title: "Not Like Us", cat: "rapint" },
  { artist: "Nicki Minaj", title: "Super Bass", cat: "rapint" },
  { artist: "Nicki Minaj", title: "Starships", cat: "rapint" },
  { artist: "Cardi B", title: "I Like It", cat: "rapint" },
  { artist: "Megan Thee Stallion", title: "Savage", cat: "rapint" },
  { artist: "Flo Rida", title: "Low", cat: "rapint" },
  { artist: "Flo Rida", title: "Whistle", cat: "rapint" },
  { artist: "Pitbull ft. Kesha", title: "Timber", cat: "rapint" },
  { artist: "will.i.am ft. Britney Spears", title: "Scream & Shout", cat: "rapint" },
  { artist: "Wiz Khalifa", title: "Black and Yellow", cat: "rapint" },
  { artist: "Tyga", title: "Taste", cat: "rapint" },
  { artist: "Sean Paul", title: "Temperature", cat: "rapint" },
  { artist: "Sean Paul", title: "Get Busy", cat: "rapint" },
  { artist: "Akon", title: "Lonely", cat: "rapint" },
  { artist: "Akon", title: "Smack That", cat: "rapint" },
  { artist: "T.I. ft. Rihanna", title: "Live Your Life", cat: "rapint" },
  { artist: "Missy Elliott", title: "Work It", cat: "rapint" },
  { artist: "AC/DC", title: "Thunderstruck", cat: "rock" },
  { artist: "AC/DC", title: "Highway to Hell", cat: "rock" },
  { artist: "Guns N' Roses", title: "Sweet Child O' Mine", cat: "rock" },
  { artist: "Metallica", title: "Nothing Else Matters", cat: "rock" },
  { artist: "Metallica", title: "Enter Sandman", cat: "rock" },
  { artist: "Led Zeppelin", title: "Stairway to Heaven", cat: "rock" },
  { artist: "Pink Floyd", title: "Another Brick in the Wall", cat: "rock" },
  { artist: "Dire Straits", title: "Sultans of Swing", cat: "rock" },
  { artist: "Eagles", title: "Hotel California", cat: "rock" },
  { artist: "Scorpions", title: "Wind of Change", cat: "rock" },
  { artist: "Scorpions", title: "Still Loving You", cat: "rock" },
  { artist: "Radiohead", title: "Creep", cat: "rock" },
  { artist: "R.E.M.", title: "Losing My Religion", cat: "rock" },
  { artist: "U2", title: "With or Without You", cat: "rock" },
  { artist: "U2", title: "Sunday Bloody Sunday", cat: "rock" },
  { artist: "Blur", title: "Song 2", cat: "rock" },
  { artist: "The Cranberries", title: "Zombie", cat: "rock" },
  { artist: "4 Non Blondes", title: "What's Up?", cat: "rock" },
  { artist: "Lenny Kravitz", title: "Are You Gonna Go My Way", cat: "rock" },
  { artist: "Lenny Kravitz", title: "Fly Away", cat: "rock" },
  { artist: "System of a Down", title: "Chop Suey!", cat: "rock" },
  { artist: "Evanescence", title: "Bring Me to Life", cat: "rock" },
  { artist: "Placebo", title: "Every You Every Me", cat: "rock" },
  { artist: "Franz Ferdinand", title: "Take Me Out", cat: "rock" },
  { artist: "Kings of Leon", title: "Sex on Fire", cat: "rock" },
  { artist: "The Black Keys", title: "Lonely Boy", cat: "rock" },
  { artist: "Twenty One Pilots", title: "Stressed Out", cat: "rock" },
  { artist: "Panic! At The Disco", title: "High Hopes", cat: "rock" },
  { artist: "Måneskin", title: "Beggin'", cat: "rock" },
  { artist: "Matmatah", title: "Lambé An Dro", cat: "rock" },
  { artist: "Saez", title: "Jeune et con", cat: "rock" },
  { artist: "Les Insus", title: "Cendrillon", cat: "rock" },
  { artist: "Trust", title: "Antisocial", cat: "rock" },
  { artist: "DJ Snake ft. Justin Bieber", title: "Let Me Love You", cat: "electro" },
  { artist: "DJ Snake", title: "Taki Taki", cat: "electro" },
  { artist: "DJ Snake & Lil Jon", title: "Turn Down for What", cat: "electro" },
  { artist: "Gala", title: "Freed from Desire", cat: "electro" },
  { artist: "Eiffel 65", title: "Blue (Da Ba Dee)", cat: "electro" },
  { artist: "Darude", title: "Sandstorm", cat: "electro" },
  { artist: "Robin Schulz", title: "Sugar", cat: "electro" },
  { artist: "Lost Frequencies", title: "Are You With Me", cat: "electro" },
  { artist: "Lost Frequencies", title: "Reality", cat: "electro" },
  { artist: "Kungs vs Cookin' on 3 Burners", title: "This Girl", cat: "electro" },
  { artist: "Kungs", title: "Never Going Home", cat: "electro" },
  { artist: "Ofenbach", title: "Be Mine", cat: "electro" },
  { artist: "Feder ft. Lyse", title: "Goodbye", cat: "electro" },
  { artist: "The Avener", title: "Fade Out Lines", cat: "electro" },
  { artist: "Synapson", title: "Djon Maya Maï", cat: "electro" },
  { artist: "Salut c'est cool", title: "Techno toujours pareil", cat: "electro" },
  { artist: "Vitalic", title: "Poney Part 1", cat: "electro" },
  { artist: "Justice", title: "D.A.N.C.E.", cat: "electro" },
  { artist: "Cassius", title: "Toop Toop", cat: "electro" },
  { artist: "Mr. Oizo", title: "Flat Beat", cat: "electro" },
  { artist: "Laurent Wolf", title: "No Stress", cat: "electro" },
  { artist: "Antoine Clamaran", title: "Gold", cat: "electro" },
  { artist: "Sash!", title: "Encore une fois", cat: "electro" },
  { artist: "Alice Deejay", title: "Better Off Alone", cat: "electro" },
  { artist: "Avicii", title: "The Nights", cat: "electro" },
  { artist: "Avicii", title: "Waiting for Love", cat: "electro" },
  { artist: "Queen", title: "Another One Bites the Dust", cat: "oldies" },
  { artist: "Queen", title: "Somebody to Love", cat: "oldies" },
  { artist: "David Bowie", title: "Let's Dance", cat: "oldies" },
  { artist: "David Bowie", title: "Heroes", cat: "oldies" },
  { artist: "Prince", title: "Purple Rain", cat: "oldies" },
  { artist: "Prince", title: "Kiss", cat: "oldies" },
  { artist: "Stevie Wonder", title: "Superstition", cat: "oldies" },
  { artist: "Stevie Wonder", title: "Isn't She Lovely", cat: "oldies" },
  { artist: "Lionel Richie", title: "Hello", cat: "oldies" },
  { artist: "Lionel Richie", title: "All Night Long", cat: "oldies" },
  { artist: "Tina Turner", title: "The Best", cat: "oldies" },
  { artist: "Tina Turner", title: "What's Love Got to Do with It", cat: "oldies" },
  { artist: "Eurythmics", title: "Sweet Dreams (Are Made of This)", cat: "oldies" },
  { artist: "Blondie", title: "Call Me", cat: "oldies" },
  { artist: "Donna Summer", title: "Hot Stuff", cat: "oldies" },
  { artist: "Chic", title: "Le Freak", cat: "oldies" },
  { artist: "Kool & The Gang", title: "Celebration", cat: "oldies" },
  { artist: "The Jackson 5", title: "I Want You Back", cat: "oldies" },
  { artist: "Marvin Gaye", title: "Sexual Healing", cat: "oldies" },
  { artist: "Ben E. King", title: "Stand by Me", cat: "oldies" },
  { artist: "Aretha Franklin", title: "Respect", cat: "oldies" },
  { artist: "Simon & Garfunkel", title: "The Sound of Silence", cat: "oldies" },
  { artist: "Fleetwood Mac", title: "Dreams", cat: "oldies" },
  { artist: "Dalida", title: "Laissez-moi danser", cat: "oldies" },
  { artist: "Dalida & Alain Delon", title: "Paroles paroles", cat: "oldies" },
  { artist: "Joe Dassin", title: "Les Champs-Élysées", cat: "oldies" },
  { artist: "Joe Dassin", title: "L'été indien", cat: "oldies" },
  { artist: "Michel Fugain", title: "Une belle histoire", cat: "oldies" },
  { artist: "Gilbert Montagné", title: "On va s'aimer", cat: "oldies" },
  { artist: "Images", title: "Les démons de minuit", cat: "oldies" },
  { artist: "Début de Soirée", title: "Nuit de folie", cat: "oldies" },
  { artist: "Philippe Katerine", title: "Louxor j'adore", cat: "oldies" },
  { artist: "Les Musclés", title: "La fête au village", cat: "oldies" },
  { artist: "Patrick Sébastien", title: "Les sardines", cat: "oldies" },
  { artist: "La Compagnie Créole", title: "Ça fait rire les oiseaux", cat: "oldies" },
  { artist: "Carlos", title: "Big bisou", cat: "oldies" },
  { artist: "Herbert Léonard", title: "Pour le plaisir", cat: "oldies" },
  { artist: "Jean-Pierre Mader", title: "Macumba", cat: "oldies" },
  { artist: "Émile et Images", title: "Jusqu'au bout de la nuit", cat: "oldies" },
  { artist: "Britney Spears", title: "Oops!... I Did It Again", cat: "oldies" },
  { artist: "Christophe", title: "Aline", cat: "oldies" },
  { artist: "Hervé Vilard", title: "Capri c'est fini", cat: "oldies" },
  { artist: "Sheila", title: "Spacer", cat: "oldies" },
  { artist: "Plastic Bertrand", title: "Ça plane pour moi", cat: "oldies" },
  { artist: "Freeze Corleone", title: "Pharmacie", cat: "rapfr" },
  { artist: "Freeze Corleone", title: "Serenity", cat: "rapfr" },
  { artist: "Freeze Corleone", title: "Framboisier", cat: "rapfr" },
  { artist: "Gazo ft. Freeze Corleone", title: "Icicle", cat: "rapfr" },
  { artist: "Gazo ft. SCH", title: "Meurtre", cat: "rapfr" },
  { artist: "Gazo", title: "Au revoir", cat: "rapfr" },
  { artist: "PLK", title: "Intro", cat: "rapfr" },
  { artist: "PLK ft. Hamza", title: "Madame", cat: "rapfr" },
  { artist: "Werenoi", title: "Pyramide", cat: "rapfr" },
  { artist: "Werenoi ft. Gazo", title: "Carré VIP", cat: "rapfr" },
  { artist: "Tiakola", title: "La même", cat: "rapfr" },
  { artist: "Tiakola ft. Gazo", title: "Mélo", cat: "rapfr" },
  { artist: "Ninho ft. Niska", title: "Chaque jour", cat: "rapfr" },
  { artist: "Ninho", title: "La retraite", cat: "rapfr" },
  { artist: "Ninho ft. Dadju", title: "N.I.L.O.S.", cat: "rapfr" },
  { artist: "Hamza", title: "Charo", cat: "rapfr" },
  { artist: "Hamza ft. Damso", title: "Saoko", cat: "rapfr" },
  { artist: "Damso", title: "Bruxelles vie", cat: "rapfr" },
  { artist: "Damso", title: "Lithopédion", cat: "rapfr" },
  { artist: "SCH", title: "Rolex", cat: "rapfr" },
  { artist: "SCH ft. Jul", title: "Bande organisée", cat: "rapfr" },
  { artist: "SDM", title: "Au revoir", cat: "rapfr" },
  { artist: "SDM ft. Ninho", title: "Billet de banque", cat: "rapfr" },
  { artist: "Lomepal", title: "Chocolat", cat: "rapfr" },
  { artist: "Lomepal ft. Ichon", title: "Tout va bien", cat: "rapfr" },
  { artist: "Nekfeu", title: "Loin du périph", cat: "rapfr" },
  { artist: "Nekfeu", title: "Iamddb", cat: "rapfr" },
  { artist: "Vald", title: "Kiff no face", cat: "rapfr" },
  { artist: "Vald", title: "PQR", cat: "rapfr" },
  { artist: "Orelsan", title: "L'odeur de l'essence", cat: "rapfr" },
  { artist: "Orelsan ft. Stromae", title: "La pluie", cat: "rapfr" },
  { artist: "Laylow", title: "Vitruve", cat: "rapfr" },
  { artist: "Laylow", title: "Bambino", cat: "rapfr" },
  { artist: "Koba LaD", title: "NRV", cat: "rapfr" },
  { artist: "Koba LaD ft. Gazo", title: "Carpe diem", cat: "rapfr" },
  { artist: "Guy2Bezbar", title: "Montagne", cat: "rapfr" },
  { artist: "Guy2Bezbar ft. Gazo", title: "Comme une étoile", cat: "rapfr" },
  { artist: "Zola", title: "Rouleau", cat: "rapfr" },
  { artist: "Zola ft. Gazo", title: "Wam", cat: "rapfr" },
  { artist: "Bosh", title: "Trappe", cat: "rapfr" },
  { artist: "Favé", title: "Solo", cat: "rapfr" },
  { artist: "Naps ft. Jul", title: "Le temps", cat: "rapfr" },
  { artist: "Soolking", title: "Liberté", cat: "rapfr" },
  { artist: "Heuss L'Enfoiré ft. JuL", title: "Turfu", cat: "rapfr" },
  { artist: "Heuss L'Enfoiré", title: "Mona Lisa", cat: "rapfr" },
  { artist: "Leto", title: "Chocolat", cat: "rapfr" },
  { artist: "Alonzo ft. Jul", title: "Bonne étoile", cat: "rapfr" },
  { artist: "Dosseh", title: "Brésil", cat: "rapfr" },
  { artist: "Dinos", title: "Sans nous", cat: "rapfr" },
  { artist: "Dinos", title: "Mains balancées", cat: "rapfr" },
  { artist: "Jazzy Bazz", title: "Panam", cat: "rapfr" },
  { artist: "Alpha Wann", title: "Une main lave l'autre", cat: "rapfr" },
  { artist: "Alkpote", title: "Supreme NTM", cat: "rapfr" },
  { artist: "Columbine", title: "Comme un avocat", cat: "rapfr" },
  { artist: "Varnish La Piscine", title: "Jackpot", cat: "rapfr" },
  { artist: "Timal ft. Koba LaD", title: "Chocolat", cat: "rapfr" },
  { artist: "Naza", title: "Chocola", cat: "rapfr" },
  { artist: "Naza ft. Gambi", title: "Paloma", cat: "rapfr" },
  { artist: "Gambi", title: "Ma loute", cat: "rapfr" },
  { artist: "Hornet La Frappe", title: "Banger", cat: "rapfr" },
  { artist: "Hornet La Frappe ft. PLK", title: "Ici ou là-bas", cat: "rapfr" },
  { artist: "Fianso ft. Kaaris", title: "Binks to Binks", cat: "rapfr" },
  { artist: "Kaaris", title: "Zeus", cat: "rapfr" },
  { artist: "Suprême NTM", title: "Qu'est-ce qu'on attend", cat: "rapfr" },
  { artist: "Akhenaton", title: "Je danse le Mia", cat: "rapfr" },
  { artist: "Oxmo Puccino", title: "Rappeur cherche femme aimante", cat: "rapfr" },
  { artist: "Abd Al Malik", title: "Gibraltar", cat: "rapfr" },
  { artist: "Kery James", title: "Si c'était à refaire", cat: "rapfr" },
  { artist: "Soprano", title: "Chocolat", cat: "rapfr" },
  { artist: "Jul", title: "Comme d'hab", cat: "rapfr" },
  { artist: "Jul ft. SCH", title: "Polémique", cat: "rapfr" },
  { artist: "Tayc", title: "Fleur froide", cat: "rapfr" },
  { artist: "Tayc", title: "Si seulement", cat: "rapfr" },
  { artist: "Dadju", title: "Gentleman 2.0", cat: "rapfr" },
  { artist: "Dadju", title: "Quand le soleil pleure", cat: "rapfr" },
  { artist: "Awa Imani", title: "Je te le donne", cat: "rapfr" },
  { artist: "Franglish ft. Dadju", title: "Sous les étoiles", cat: "rapfr" },
  { artist: "Keblack", title: "Chocolat", cat: "rapfr" },
  { artist: "Keblack ft. Ninho", title: "Chocolat", cat: "rapfr" },
  { artist: "Imen ES", title: "Maintenant", cat: "rapfr" },
  { artist: "Imen ES ft. Ninho", title: "Ma vie", cat: "rapfr" },
  { artist: "Maes", title: "Rooftop", cat: "rapfr" },
  { artist: "Maes ft. Ninho", title: "Les derniers salopards", cat: "rapfr" },
  { artist: "Lacrim", title: "Ripro Vol. 6", cat: "rapfr" },
  { artist: "La Fouine ft. Zaho", title: "Reste en chien", cat: "rapfr" },
  { artist: "Seth Gueko", title: "Bar Floréal", cat: "rapfr" },
  { artist: "Olivia Rodrigo", title: "vampire", cat: "popint" },
  { artist: "Olivia Rodrigo", title: "traitor", cat: "popint" },
  { artist: "Sabrina Carpenter", title: "Please Please Please", cat: "popint" },
  { artist: "Sabrina Carpenter", title: "Taste", cat: "popint" },
  { artist: "Chappell Roan", title: "HOT TO GO!", cat: "popint" },
  { artist: "Chappell Roan", title: "Pink Pony Club", cat: "popint" },
  { artist: "Gracie Abrams", title: "That's So True", cat: "popint" },
  { artist: "Charli XCX", title: "360", cat: "popint" },
  { artist: "Charli XCX", title: "Boom Clap", cat: "popint" },
  { artist: "Benson Boone", title: "Ghost Town", cat: "popint" },
  { artist: "Teddy Swims", title: "The Door", cat: "popint" },
  { artist: "Jack Johnson", title: "Better Together", cat: "popint" },
  { artist: "Jack Johnson", title: "Upside Down", cat: "popint" },
  { artist: "Jason Mraz", title: "I'm Yours", cat: "popint" },
  { artist: "Colbie Caillat", title: "Bubbly", cat: "popint" },
  { artist: "Owl City", title: "Fireflies", cat: "popint" },
  { artist: "Foster The People", title: "Pumped Up Kicks", cat: "popint" },
  { artist: "Gotye ft. Kimbra", title: "Somebody That I Used to Know", cat: "popint" },
  { artist: "Of Monsters and Men", title: "Little Talks", cat: "popint" },
  { artist: "Vance Joy", title: "Riptide", cat: "popint" },
  { artist: "Hozier", title: "Too Sweet", cat: "popint" },
  { artist: "Troye Sivan", title: "Rush", cat: "popint" },
  { artist: "Mitski", title: "My Love Mine All Mine", cat: "popint" },
  { artist: "SZA", title: "Good Days", cat: "popint" },
  { artist: "SZA", title: "Snooze", cat: "popint" },
  { artist: "Dua Lipa", title: "Houdini", cat: "popint" },
  { artist: "Dua Lipa", title: "Training Season", cat: "popint" },
  { artist: "Taylor Swift", title: "Cruel Summer", cat: "popint" },
  { artist: "Taylor Swift", title: "cardigan", cat: "popint" },
  { artist: "Taylor Swift", title: "Love Story", cat: "popint" },
  { artist: "Beyoncé", title: "BREAK MY SOUL", cat: "popint" },
  { artist: "Rosalia", title: "Con Altura", cat: "popint" },
  { artist: "Bad Bunny", title: "Me Porto Bonito", cat: "popint" },
  { artist: "Karol G & Nicki Minaj", title: "Tusa", cat: "popint" },
  { artist: "Cardi B ft. Megan Thee Stallion", title: "WAP", cat: "rapint" },
  { artist: "Cardi B", title: "Money", cat: "rapint" },
  { artist: "Doja Cat", title: "Planet Her", cat: "rapint" },
  { artist: "Doja Cat ft. The Weeknd", title: "You Right", cat: "rapint" },
  { artist: "Ice Spice", title: "Munch (Feelin' U)", cat: "rapint" },
  { artist: "GloRilla", title: "FNF (Let's Go)", cat: "rapint" },
  { artist: "Kendrick Lamar", title: "Alright", cat: "rapint" },
  { artist: "Kendrick Lamar", title: "DNA.", cat: "rapint" },
  { artist: "Travis Scott", title: "ANTIDOTE", cat: "rapint" },
  { artist: "Travis Scott", title: "Goosebumps", cat: "rapint" },
  { artist: "J. Cole", title: "Love Yourz", cat: "rapint" },
  { artist: "J. Cole", title: "No Role Modelz", cat: "rapint" },
  { artist: "21 Savage ft. Post Malone", title: "Rockstar", cat: "rapint" },
  { artist: "Lil Baby", title: "Drip Too Hard", cat: "rapint" },
  { artist: "Roddy Ricch", title: "The Box", cat: "rapint" },
  { artist: "Future ft. Drake", title: "Life Is Good", cat: "rapint" },
  { artist: "Drake ft. Lil Durk", title: "Laugh Now Cry Later", cat: "rapint" },
  { artist: "Polo G", title: "Pop Out", cat: "rapint" },
  { artist: "A Boogie Wit da Hoodie", title: "Look Back at It", cat: "rapint" },
  { artist: "Juice WRLD", title: "Lucid Dreams", cat: "rapint" },
  { artist: "Juice WRLD", title: "Legends", cat: "rapint" },
  { artist: "XXXTentacion", title: "SAD!", cat: "rapint" },
  { artist: "Pop Smoke", title: "Dior", cat: "rapint" },
  { artist: "Pop Smoke ft. Quavo", title: "Shake the Room", cat: "rapint" },
  { artist: "Nicki Minaj ft. Drake & Lil Wayne", title: "Truffle Butter", cat: "rapint" },
  { artist: "Migos", title: "Bad and Boujee", cat: "rapint" },
  { artist: "Young Thug", title: "Havana", cat: "rapint" },
  { artist: "Lil Wayne", title: "A Milli", cat: "rapint" },
  { artist: "Rick Ross", title: "Hustlin'", cat: "rapint" },
  { artist: "T-Pain ft. Yung Joc", title: "Buy U a Drank", cat: "rapint" },
  { artist: "Oasis", title: "Champagne Supernova", cat: "rock" },
  { artist: "Coldplay", title: "Clocks", cat: "rock" },
  { artist: "Coldplay", title: "A Sky Full of Stars", cat: "rock" },
  { artist: "Coldplay", title: "Hymn for the Weekend", cat: "rock" },
  { artist: "Arctic Monkeys", title: "R U Mine?", cat: "rock" },
  { artist: "Arctic Monkeys", title: "505", cat: "rock" },
  { artist: "The Strokes", title: "Last Nite", cat: "rock" },
  { artist: "The Strokes", title: "Reptilia", cat: "rock" },
  { artist: "The 1975", title: "Somebody Else", cat: "rock" },
  { artist: "The 1975", title: "Chocolate", cat: "rock" },
  { artist: "Cage the Elephant", title: "Shake Me Down", cat: "rock" },
  { artist: "Glass Animals", title: "Gooey", cat: "rock" },
  { artist: "Tame Impala", title: "The Less I Know the Better", cat: "rock" },
  { artist: "Tame Impala", title: "Feels Like We Only Go Backwards", cat: "rock" },
  { artist: "Mac DeMarco", title: "Chamber of Reflection", cat: "rock" },
  { artist: "Rex Orange County", title: "Loving Is Easy", cat: "rock" },
  { artist: "Wallows", title: "Are You Bored Yet?", cat: "rock" },
  { artist: "beabadoobee", title: "Coffee", cat: "rock" },
  { artist: "Surf Curse", title: "Freaks", cat: "rock" },
  { artist: "TV Girrl", title: "Say Yes to Heaven", cat: "rock" },
  { artist: "Lana Del Rey", title: "Summertime Sadness", cat: "rock" },
  { artist: "Lana Del Rey", title: "Young and Beautiful", cat: "rock" },
  { artist: "Lana Del Rey", title: "Video Games", cat: "rock" },
  { artist: "Paramore", title: "Decode", cat: "rock" },
  { artist: "Paramore", title: "Still Into You", cat: "rock" },
  { artist: "My Chemical Romance", title: "Welcome to the Black Parade", cat: "rock" },
  { artist: "My Chemical Romance", title: "I'm Not Okay (I Promise)", cat: "rock" },
  { artist: "Fall Out Boy", title: "Sugar We're Goin Down", cat: "rock" },
  { artist: "Fall Out Boy", title: "Dance, Dance", cat: "rock" },
  { artist: "Sum 41", title: "Fat Lip", cat: "rock" },
  { artist: "Blink-182", title: "All the Small Things", cat: "rock" },
  { artist: "Blink-182", title: "I Miss You", cat: "rock" },
  { artist: "Simple Plan", title: "Welcome to My Life", cat: "rock" },
  { artist: "Nickelback", title: "How You Remind Me", cat: "rock" },
  { artist: "Three Days Grace", title: "Animal I Have Become", cat: "rock" },
  { artist: "Musique", title: "In the Air Tonight", cat: "rock" },
  { artist: "Phil Collins", title: "In the Air Tonight", cat: "rock" },
  { artist: "Fleetwood Mac", title: "Go Your Own Way", cat: "rock" },
  { artist: "Rage Against the Machine", title: "Killing in the Name", cat: "rock" },
  { artist: "Audioslave", title: "Like a Stone", cat: "rock" },
  { artist: "Imagine Dragons", title: "Enemy", cat: "rock" },
  { artist: "Imagine Dragons", title: "Thunder", cat: "rock" },
  { artist: "Bastille", title: "Pompeii", cat: "rock" },
  { artist: "Mumford & Sons", title: "The Cave", cat: "rock" },
  { artist: "Mumford & Sons", title: "I Will Wait", cat: "rock" },
  { artist: "Ed Sheeran & Justin Bieber", title: "I Don't Care", cat: "rock" },
  { artist: "Indochine", title: "College Boy", cat: "rock" },
  { artist: "Indochine", title: "Le manoir", cat: "rock" },
  { artist: "Téléphone", title: "Un autre monde", cat: "rock" },
  { artist: "Noir Désir", title: "Les paradis", cat: "rock" },
  { artist: "Martin Garrix", title: "Animals", cat: "electro" },
  { artist: "Martin Garrix & Dua Lipa", title: "Scared to Be Lonely", cat: "electro" },
  { artist: "Tiësto", title: "The Business", cat: "electro" },
  { artist: "Fisher", title: "Losing It", cat: "electro" },
  { artist: "Disclosure ft. Sam Smith", title: "Latch", cat: "electro" },
  { artist: "Flume ft. Kai", title: "Never Be Like You", cat: "electro" },
  { artist: "Kygo ft. Selena Gomez", title: "It Ain't Me", cat: "electro" },
  { artist: "Kygo ft. Ellie Goulding", title: "First Time", cat: "electro" },
  { artist: "Ellie Goulding", title: "Burn", cat: "electro" },
  { artist: "Ellie Goulding", title: "Lights", cat: "electro" },
  { artist: "Zedd ft. Foxes", title: "Clarity", cat: "electro" },
  { artist: "Zedd & Alessia Cara", title: "Stay the Night", cat: "electro" },
  { artist: "Marshmello & Anne-Marie", title: "FRIENDS", cat: "electro" },
  { artist: "Galantis", title: "Runaway (U & I)", cat: "electro" },
  { artist: "Diplo & Sidepiece", title: "On My Mind", cat: "electro" },
  { artist: "WizKid ft. Tiwa Savage", title: "Fever", cat: "electro" },
  { artist: "Bob Marley & The Wailers", title: "One Love", cat: "electro" },
  { artist: "ClockClock", title: "No More Lies", cat: "electro" },
  { artist: "Dj Alok", title: "Don't You Dare", cat: "electro" },
  { artist: "Angèle & Dua Lipa", title: "Fever", cat: "electro" },
  { artist: "Lomepal & Angèle", title: "Tristesse", cat: "electro" },
  { artist: "I Hate Models", title: "Circles", cat: "electro" },
  { artist: "Gesaffelstein", title: "Pursuit", cat: "electro" },
  { artist: "Whitney Houston", title: "Greatest Love of All", cat: "oldies" },
  { artist: "ABBA", title: "Voulez-Vous", cat: "oldies" },
  { artist: "ABBA", title: "The Winner Takes It All", cat: "oldies" },
  { artist: "The Beatles", title: "Come Together", cat: "oldies" },
  { artist: "The Beatles", title: "Yesterday", cat: "oldies" },
  { artist: "Led Zeppelin", title: "Kashmir", cat: "oldies" },
  { artist: "Elvis Presley", title: "Jailhouse Rock", cat: "oldies" },
  { artist: "Bob Dylan", title: "Blowin' in the Wind", cat: "oldies" },
  { artist: "Marvin Gaye", title: "Let's Get It On", cat: "oldies" },
  { artist: "Aretha Franklin", title: "Think", cat: "oldies" },
  { artist: "James Brown", title: "I Got You (I Feel Good)", cat: "oldies" },
  { artist: "Ray Charles", title: "Hit the Road Jack", cat: "oldies" },
  { artist: "Louis Armstrong", title: "What a Wonderful World", cat: "oldies" },
  { artist: "Jacques Dutronc", title: "Il est cinq heures, Paris s'éveille", cat: "oldies" },
  { artist: "Charles Aznavour", title: "La bohème", cat: "oldies" },
  { artist: "Georges Brassens", title: "Les copains d'abord", cat: "oldies" },
  { artist: "Léo Ferré", title: "Avec le temps", cat: "oldies" },
  { artist: "Françoise Hardy", title: "Tous les garçons et les filles", cat: "oldies" },
  { artist: "Sylvie Vartan", title: "Irrésistiblement", cat: "oldies" },
  { artist: "Johnny Hallyday", title: "Que je t'aime", cat: "oldies" },
  { artist: "Johnny Hallyday", title: "Mon amour", cat: "oldies" },
  { artist: "Michel Polnareff", title: "Tous les bateaux, tous les oiseaux", cat: "oldies" },
  { artist: "Gainsbourg & Birkin", title: "Je t'aime... moi non plus", cat: "oldies" },
  { artist: "Téléphone", title: "Hygiaphone", cat: "oldies" },
  { artist: "Nino Ferrer", title: "Le Sud", cat: "oldies" },
  { artist: "Gérard Lenorman", title: "Michèle", cat: "oldies" },
  { artist: "Dorothée", title: "Hou la menteuse", cat: "oldies" },
  { artist: "Dorothée", title: "Aloha l'île enchantée", cat: "oldies" },
  { artist: "Chantal Goya", title: "Récréation", cat: "oldies" },
  { artist: "Herbert Pagani", title: "Alitalia", cat: "oldies" },
  { artist: "Rita Mitsouko", title: "Andy", cat: "oldies" },
  { artist: "Niagara", title: "Quand la ville dort", cat: "oldies" },
  { artist: "Indochine", title: "3 nuits par semaine", cat: "oldies" },
  { artist: "Étienne Daho", title: "Week-end à Rome", cat: "oldies" },
  { artist: "Pascal Obispo", title: "Fan", cat: "popfr" },
  { artist: "Zazie", title: "Rue de la paix", cat: "popfr" },
  { artist: "Kareen Antonn", title: "Si demain", cat: "popfr" },
  { artist: "Aya Nakamura", title: "Copines", cat: "popfr" },
  { artist: "Aya Nakamura", title: "Jolie nana", cat: "popfr" },
  { artist: "Angèle", title: "Tout oublier", cat: "popfr" },
  { artist: "Angèle", title: "Libre", cat: "popfr" },
  { artist: "Clara Luciani", title: "Respire encore", cat: "popfr" },
  { artist: "Clara Luciani", title: "Ma sœur", cat: "popfr" },
  { artist: "Stromae", title: "Tous les mêmes", cat: "popfr" },
  { artist: "Stromae", title: "L'enfer", cat: "popfr" },
  { artist: "Louane", title: "Si t'étais là", cat: "popfr" },
  { artist: "Hoshi", title: "Il suffit d'y croire", cat: "popfr" },
  { artist: "Pomme", title: "Anxiété", cat: "popfr" },
  { artist: "Juliette Armanet", title: "L'amour en solitaire", cat: "popfr" },
  { artist: "Eddy de Pretto", title: "Random", cat: "popfr" },
  { artist: "Videoclub", title: "Amour plastique", cat: "popfr" },
  { artist: "Suzane", title: "SLT", cat: "popfr" },
  { artist: "Pierre Garnier", title: "Ceux qu'on était", cat: "popfr" },
  { artist: "Vitaa", title: "Game Over", cat: "popfr" },
  { artist: "Kendji Girac", title: "Que Dieu me pardonne", cat: "popfr" },
  { artist: "Kendji Girac & Vianney", title: "Le feu", cat: "popfr" },
  { artist: "Patrick Bruel", title: "Qui a le droit", cat: "popfr" },
  { artist: "Garou & Céline Dion", title: "Sous le vent", cat: "popfr" },
  { artist: "Céline Dion", title: "On ne change pas", cat: "popfr" },
  { artist: "M", title: "Qui de nous deux", cat: "popfr" },
  { artist: "M", title: "Est-ce que c'est ça", cat: "popfr" },
  { artist: "Benjamin Biolay", title: "Comment est ta peine ?", cat: "popfr" },
  { artist: "Étienne Daho", title: "Duel au soleil", cat: "popfr" },
  { artist: "Vanessa Paradis", title: "Joe le taxi", cat: "popfr" },
  { artist: "Vanessa Paradis", title: "Divine idylle", cat: "popfr" },
  { artist: "Olivia Ruiz", title: "La femme chocolat", cat: "popfr" },
  { artist: "Camille", title: "Ta douleur", cat: "popfr" },
  { artist: "Yael Naim", title: "New Soul", cat: "popfr" },
  { artist: "Christophe Willem", title: "Berlin", cat: "popfr" },
  { artist: "Shy'm", title: "Et alors !", cat: "popfr" },
  { artist: "Matt Pokora", title: "Elle me contrôle", cat: "popfr" },
  { artist: "Leslie", title: "Sobri", cat: "popfr" },
  { artist: "Nâdiya", title: "Roc", cat: "popfr" },
  { artist: "Lorie", title: "Sur un air latino", cat: "popfr" },
  { artist: "Priscilla", title: "Bric à brac", cat: "popfr" },
  { artist: "Yannick", title: "Ces soirées-là", cat: "popfr" },
  { artist: "Tragédie", title: "Hey oh", cat: "popfr" },
  { artist: "K-Maro", title: "Femme Like U", cat: "popfr" },
  { artist: "Matt Houston", title: "R&B 2 rue", cat: "popfr" },
  { artist: "Willy Denzey", title: "Le mur du son", cat: "popfr" },
  { artist: "Ninho", title: "Jefe", cat: "rapfr" },
  { artist: "Ninho ft. Naps", title: "Elle a mal", cat: "rapfr" },
  { artist: "Gazo & Tiakola", title: "CHOP", cat: "rapfr" },
  { artist: "SDM", title: "Cartier santos", cat: "rapfr" },
  { artist: "SDM", title: "Redescends", cat: "rapfr" },
  { artist: "Werenoi ft. Damso", title: "Solitaire", cat: "rapfr" },
  { artist: "Josman", title: "Intro (000)", cat: "rapfr" },
  { artist: "Josman", title: "J'aime bien", cat: "rapfr" },
  { artist: "Luidji", title: "Bonne journée", cat: "rapfr" },
  { artist: "Luidji", title: "Élévation", cat: "rapfr" },
  { artist: "La Fève", title: "Mauvais payeur", cat: "rapfr" },
  { artist: "Khali", title: "Bipolaire", cat: "rapfr" },
  { artist: "SCH", title: "Otto", cat: "rapfr" },
  { artist: "SCH", title: "Comme si de rien", cat: "rapfr" },
  { artist: "Jul", title: "La bandite", cat: "rapfr" },
  { artist: "Jul", title: "Wesh alors", cat: "rapfr" },
  { artist: "Naps", title: "Best Life", cat: "rapfr" },
  { artist: "Soso Maness ft. PLK", title: "Zumba Cafew", cat: "rapfr" },
  { artist: "Soso Maness", title: "Petrouchka", cat: "rapfr" },
  { artist: "13 Organisé", title: "Je suis Marseille", cat: "rapfr" },
  { artist: "L'Algérino", title: "Les menottes", cat: "rapfr" },
  { artist: "L'Algérino", title: "Va bene", cat: "rapfr" },
  { artist: "Mister You", title: "Le prince", cat: "rapfr" },
  { artist: "Sadek", title: "Nique le casino", cat: "rapfr" },
  { artist: "Sofiane", title: "Toka", cat: "rapfr" },
  { artist: "Kalash", title: "Mwaka Moon", cat: "rapfr" },
  { artist: "Kalash ft. Damso", title: "Mwaka Moon", cat: "rapfr" },
  { artist: "Shay", title: "Jolie Garce", cat: "rapfr" },
  { artist: "Shay ft. Niska", title: "Liquide", cat: "rapfr" },
  { artist: "Aya Nakamura ft. Damso", title: "Dégaine", cat: "rapfr" },
  { artist: "Rim'K ft. Ninho", title: "Cactus", cat: "rapfr" },
  { artist: "Mac Tyer", title: "Je suis un pro", cat: "rapfr" },
  { artist: "Ateyaba", title: "Everest", cat: "rapfr" },
  { artist: "Népal", title: "Sundance", cat: "rapfr" },
  { artist: "Lujipeka", title: "Putain d'époque", cat: "rapfr" },
  { artist: "Georgio", title: "Héra", cat: "rapfr" },
  { artist: "Bekar", title: "Plus tard", cat: "rapfr" },
  { artist: "Zamdane", title: "Couleurs", cat: "rapfr" },
  { artist: "ElGrandeToto", title: "Blueberry", cat: "rapfr" },
  { artist: "Rilès", title: "Should I", cat: "rapfr" },
  { artist: "Rounhaa", title: "Alba", cat: "rapfr" },
  { artist: "So La Lune", title: "Émeraude", cat: "rapfr" },
  { artist: "Yamê", title: "Bécane", cat: "rapfr" },
  { artist: "Theodora", title: "Kongolese sous BBL", cat: "rapfr" },
  { artist: "The Weeknd ft. Daft Punk", title: "I Feel It Coming", cat: "popint" },
  { artist: "The Weeknd", title: "Can't Feel My Face", cat: "popint" },
  { artist: "The Weeknd ft. Ariana Grande", title: "Die For You", cat: "popint" },
  { artist: "Rihanna ft. Calvin Harris", title: "We Found Love", cat: "popint" },
  { artist: "Rihanna", title: "Don't Stop the Music", cat: "popint" },
  { artist: "Rihanna ft. Drake", title: "Work", cat: "popint" },
  { artist: "Beyoncé", title: "CUFF IT", cat: "popint" },
  { artist: "Ariana Grande", title: "Into You", cat: "popint" },
  { artist: "Ariana Grande", title: "we can't be friends", cat: "popint" },
  { artist: "Selena Gomez", title: "Lose You to Love Me", cat: "popint" },
  { artist: "Demi Lovato", title: "Sorry Not Sorry", cat: "popint" },
  { artist: "Halsey", title: "Without Me", cat: "popint" },
  { artist: "Bebe Rexha & David Guetta", title: "I'm Good (Blue)", cat: "popint" },
  { artist: "Anne-Marie", title: "2002", cat: "popint" },
  { artist: "Jessie J ft. B.o.B", title: "Price Tag", cat: "popint" },
  { artist: "Jessie J, Ariana Grande, Nicki Minaj", title: "Bang Bang", cat: "popint" },
  { artist: "Rita Ora", title: "Let You Love Me", cat: "popint" },
  { artist: "Ella Henderson", title: "Ghost", cat: "popint" },
  { artist: "Birdy", title: "Skinny Love", cat: "popint" },
  { artist: "Tom Odell", title: "Another Love", cat: "popint" },
  { artist: "George Ezra", title: "Budapest", cat: "popint" },
  { artist: "George Ezra", title: "Shotgun", cat: "popint" },
  { artist: "Years & Years", title: "King", cat: "popint" },
  { artist: "MIKA", title: "Grace Kelly", cat: "popint" },
  { artist: "MIKA", title: "Relax, Take It Easy", cat: "popint" },
  { artist: "MIKA", title: "Elle me dit", cat: "popint" },
  { artist: "Robbie Williams", title: "Angels", cat: "popint" },
  { artist: "Robbie Williams", title: "Feel", cat: "popint" },
  { artist: "Craig David", title: "7 Days", cat: "popint" },
  { artist: "Ne-Yo", title: "So Sick", cat: "popint" },
  { artist: "Jason Derulo", title: "Whatcha Say", cat: "popint" },
  { artist: "Chris Brown", title: "With You", cat: "popint" },
  { artist: "Timbaland ft. OneRepublic", title: "Apologize", cat: "popint" },
  { artist: "OneRepublic", title: "Secrets", cat: "popint" },
  { artist: "The Script", title: "Hall of Fame", cat: "popint" },
  { artist: "Train", title: "Hey, Soul Sister", cat: "popint" },
  { artist: "Bruno Mars", title: "The Lazy Song", cat: "popint" },
  { artist: "Bruno Mars", title: "Grenade", cat: "popint" },
  { artist: "Bruno Mars", title: "24K Magic", cat: "popint" },
  { artist: "Meghan Trainor", title: "Made You Look", cat: "popint" },
  { artist: "Lizzo", title: "About Damn Time", cat: "popint" },
  { artist: "Harry Styles", title: "Adore You", cat: "popint" },
  { artist: "Shawn Mendes", title: "Stitches", cat: "popint" },
  { artist: "Shawn Mendes", title: "Treat You Better", cat: "popint" },
  { artist: "Lukas Graham", title: "7 Years", cat: "popint" },
  { artist: "Rag'n'Bone Man", title: "Giant", cat: "popint" },
  { artist: "Sam Smith & Kim Petras", title: "Unholy", cat: "popint" },
  { artist: "Sam Smith", title: "I'm Not the Only One", cat: "popint" },
  { artist: "Adele", title: "Skyfall", cat: "popint" },
  { artist: "Adele", title: "When We Were Young", cat: "popint" },
  { artist: "Sigrid", title: "Strangers", cat: "popint" },
  { artist: "Aurora", title: "Runaway", cat: "popint" },
  { artist: "Coldplay & BTS", title: "My Universe", cat: "popint" },
  { artist: "BTS", title: "Dynamite", cat: "popint" },
  { artist: "BLACKPINK", title: "DDU-DU DDU-DU", cat: "popint" },
  { artist: "PSY", title: "Gangnam Style", cat: "popint" },
  { artist: "Eminem", title: "Not Afraid", cat: "rapint" },
  { artist: "Eminem ft. Nate Dogg", title: "Till I Collapse", cat: "rapint" },
  { artist: "Dr. Dre ft. Eminem", title: "Forgot About Dre", cat: "rapint" },
  { artist: "Kendrick Lamar & SZA", title: "All the Stars", cat: "rapint" },
  { artist: "Kendrick Lamar", title: "Money Trees", cat: "rapint" },
  { artist: "Drake", title: "In My Feelings", cat: "rapint" },
  { artist: "Drake ft. Wizkid & Kyla", title: "One Dance", cat: "rapint" },
  { artist: "Drake", title: "Started From the Bottom", cat: "rapint" },
  { artist: "Kanye West ft. Jamie Foxx", title: "Gold Digger", cat: "rapint" },
  { artist: "Kanye West", title: "Heartless", cat: "rapint" },
  { artist: "Kanye West", title: "Runaway", cat: "rapint" },
  { artist: "Jay-Z ft. Kanye West", title: "N****s in Paris", cat: "rapint" },
  { artist: "50 Cent ft. Nate Dogg", title: "21 Questions", cat: "rapint" },
  { artist: "50 Cent", title: "P.I.M.P.", cat: "rapint" },
  { artist: "The Game ft. 50 Cent", title: "How We Do", cat: "rapint" },
  { artist: "Snoop Dogg ft. Pharrell", title: "Beautiful", cat: "rapint" },
  { artist: "Nate Dogg & Warren G", title: "Regulate", cat: "rapint" },
  { artist: "DMX", title: "X Gon' Give It to Ya", cat: "rapint" },
  { artist: "DMX", title: "Ruff Ryders' Anthem", cat: "rapint" },
  { artist: "Ja Rule ft. Ashanti", title: "Always on Time", cat: "rapint" },
  { artist: "Nelly ft. Kelly Rowland", title: "Dilemma", cat: "rapint" },
  { artist: "Nelly", title: "Ride wit Me", cat: "rapint" },
  { artist: "Ludacris", title: "Move Bitch", cat: "rapint" },
  { artist: "Chamillionaire", title: "Ridin'", cat: "rapint" },
  { artist: "Soulja Boy", title: "Crank That", cat: "rapint" },
  { artist: "Kid Cudi", title: "Day 'n' Nite", cat: "rapint" },
  { artist: "Kid Cudi", title: "Pursuit of Happiness", cat: "rapint" },
  { artist: "Wiz Khalifa ft. Snoop Dogg", title: "Young, Wild & Free", cat: "rapint" },
  { artist: "Mac Miller", title: "Self Care", cat: "rapint" },
  { artist: "Tyler, The Creator", title: "EARFQUAKE", cat: "rapint" },
  { artist: "A$AP Rocky", title: "Praise the Lord", cat: "rapint" },
  { artist: "21 Savage", title: "a lot", cat: "rapint" },
  { artist: "Central Cee", title: "Doja", cat: "rapint" },
  { artist: "Central Cee & Dave", title: "Sprinter", cat: "rapint" },
  { artist: "Dave", title: "Location", cat: "rapint" },
  { artist: "Stormzy", title: "Vossi Bop", cat: "rapint" },
  { artist: "Queen", title: "Radio Ga Ga", cat: "rock" },
  { artist: "Queen & David Bowie", title: "Under Pressure", cat: "rock" },
  { artist: "The Who", title: "Baba O'Riley", cat: "rock" },
  { artist: "Deep Purple", title: "Smoke on the Water", cat: "rock" },
  { artist: "Black Sabbath", title: "Paranoid", cat: "rock" },
  { artist: "Ozzy Osbourne", title: "Crazy Train", cat: "rock" },
  { artist: "Iron Maiden", title: "The Trooper", cat: "rock" },
  { artist: "Kiss", title: "I Was Made for Lovin' You", cat: "rock" },
  { artist: "Aerosmith", title: "I Don't Want to Miss a Thing", cat: "rock" },
  { artist: "Aerosmith", title: "Dream On", cat: "rock" },
  { artist: "Bryan Adams", title: "Summer of '69", cat: "rock" },
  { artist: "Lenny Kravitz", title: "American Woman", cat: "rock" },
  { artist: "The Offspring", title: "Pretty Fly (For a White Guy)", cat: "rock" },
  { artist: "The Offspring", title: "The Kids Aren't Alright", cat: "rock" },
  { artist: "Limp Bizkit", title: "Rollin'", cat: "rock" },
  { artist: "Papa Roach", title: "Last Resort", cat: "rock" },
  { artist: "Slipknot", title: "Duality", cat: "rock" },
  { artist: "Korn", title: "Freak on a Leash", cat: "rock" },
  { artist: "Marilyn Manson", title: "The Beautiful People", cat: "rock" },
  { artist: "Rammstein", title: "Du hast", cat: "rock" },
  { artist: "Rammstein", title: "Sonne", cat: "rock" },
  { artist: "Gojira", title: "Stranded", cat: "rock" },
  { artist: "Ghost", title: "Square Hammer", cat: "rock" },
  { artist: "Greta Van Fleet", title: "Highway Tune", cat: "rock" },
  { artist: "Wolfmother", title: "Woman", cat: "rock" },
  { artist: "Jet", title: "Are You Gonna Be My Girl", cat: "rock" },
  { artist: "The Hives", title: "Hate to Say I Told You So", cat: "rock" },
  { artist: "Kaiser Chiefs", title: "Ruby", cat: "rock" },
  { artist: "Kasabian", title: "Fire", cat: "rock" },
  { artist: "The Fratellis", title: "Chelsea Dagger", cat: "rock" },
  { artist: "Vampire Weekend", title: "A-Punk", cat: "rock" },
  { artist: "MGMT", title: "Electric Feel", cat: "rock" },
  { artist: "MGMT", title: "Kids", cat: "rock" },
  { artist: "Empire of the Sun", title: "We Are the People", cat: "rock" },
  { artist: "alt-J", title: "Breezeblocks", cat: "rock" },
  { artist: "Portugal. The Man", title: "Feel It Still", cat: "rock" },
  { artist: "Hozier", title: "Cherry Wine", cat: "rock" },
  { artist: "Radiohead", title: "Karma Police", cat: "rock" },
  { artist: "Radiohead", title: "No Surprises", cat: "rock" },
  { artist: "The Verve", title: "Bitter Sweet Symphony", cat: "rock" },
  { artist: "Dire Straits", title: "Money for Nothing", cat: "rock" },
  { artist: "Daft Punk ft. Pharrell Williams", title: "Lose Yourself to Dance", cat: "electro" },
  { artist: "Daft Punk", title: "Instant Crush", cat: "electro" },
  { artist: "Daft Punk", title: "Digital Love", cat: "electro" },
  { artist: "Justice", title: "Genesis", cat: "electro" },
  { artist: "Justice ft. Tame Impala", title: "One Night/All Night", cat: "electro" },
  { artist: "Breakbot", title: "Baby I'm Yours", cat: "electro" },
  { artist: "Myd", title: "The Sun", cat: "electro" },
  { artist: "Folamour", title: "Devoted to U", cat: "electro" },
  { artist: "FKJ", title: "Tadow", cat: "electro" },
  { artist: "Møme", title: "Aloha", cat: "electro" },
  { artist: "Klingande", title: "Jubel", cat: "electro" },
  { artist: "Bakermat", title: "One Day (Vandaag)", cat: "electro" },
  { artist: "Robin Schulz ft. Jasmine Thompson", title: "Sun Goes Down", cat: "electro" },
  { artist: "Felix Jaehn ft. Jasmine Thompson", title: "Ain't Nobody", cat: "electro" },
  { artist: "Duke Dumont", title: "Ocean Drive", cat: "electro" },
  { artist: "Jonas Blue ft. Dakota", title: "Fast Car", cat: "electro" },
  { artist: "Sigala", title: "Easy Love", cat: "electro" },
  { artist: "Years & Years", title: "Desire", cat: "electro" },
  { artist: "Purple Disco Machine", title: "Hypnotized", cat: "electro" },
  { artist: "Purple Disco Machine", title: "In the Dark", cat: "electro" },
  { artist: "Boris Brejcha", title: "Gravity", cat: "electro" },
  { artist: "Charlotte de Witte", title: "Doppler", cat: "electro" },
  { artist: "Paul Kalkbrenner", title: "Sky and Sand", cat: "electro" },
  { artist: "Fred again..", title: "Turn On the Lights again..", cat: "electro" },
  { artist: "Skrillex", title: "Bangarang", cat: "electro" },
  { artist: "deadmau5", title: "Strobe", cat: "electro" },
  { artist: "Eric Prydz", title: "Call on Me", cat: "electro" },
  { artist: "Benny Benassi", title: "Satisfaction", cat: "electro" },
  { artist: "Crystal Waters", title: "Gypsy Woman", cat: "electro" },
  { artist: "Technotronic", title: "Pump Up the Jam", cat: "electro" },
  { artist: "Snap!", title: "Rhythm Is a Dancer", cat: "electro" },
  { artist: "Haddaway", title: "What Is Love", cat: "electro" },
  { artist: "Corona", title: "The Rhythm of the Night", cat: "electro" },
  { artist: "2 Unlimited", title: "No Limit", cat: "electro" },
  { artist: "Vengaboys", title: "Boom, Boom, Boom, Boom!!", cat: "electro" },
  { artist: "Scatman John", title: "Scatman", cat: "electro" },
  { artist: "Michael Jackson", title: "Smooth Criminal", cat: "oldies" },
  { artist: "Michael Jackson", title: "Bad", cat: "oldies" },
  { artist: "Michael Jackson", title: "They Don't Care About Us", cat: "oldies" },
  { artist: "Stevie Wonder", title: "Sir Duke", cat: "oldies" },
  { artist: "Earth, Wind & Fire", title: "Boogie Wonderland", cat: "oldies" },
  { artist: "Diana Ross", title: "Upside Down", cat: "oldies" },
  { artist: "The Supremes", title: "You Can't Hurry Love", cat: "oldies" },
  { artist: "Otis Redding", title: "(Sittin' On) The Dock of the Bay", cat: "oldies" },
  { artist: "Percy Sledge", title: "When a Man Loves a Woman", cat: "oldies" },
  { artist: "The Temptations", title: "My Girl", cat: "oldies" },
  { artist: "Frank Sinatra", title: "My Way", cat: "oldies" },
  { artist: "Frank Sinatra", title: "Fly Me to the Moon", cat: "oldies" },
  { artist: "Nancy Sinatra", title: "Bang Bang", cat: "oldies" },
  { artist: "Chuck Berry", title: "Johnny B. Goode", cat: "oldies" },
  { artist: "Little Richard", title: "Tutti Frutti", cat: "oldies" },
  { artist: "Jerry Lee Lewis", title: "Great Balls of Fire", cat: "oldies" },
  { artist: "The Beach Boys", title: "Good Vibrations", cat: "oldies" },
  { artist: "The Mamas & The Papas", title: "California Dreamin'", cat: "oldies" },
  { artist: "Creedence Clearwater Revival", title: "Fortunate Son", cat: "oldies" },
  { artist: "The Animals", title: "The House of the Rising Sun", cat: "oldies" },
  { artist: "Bee Gees", title: "How Deep Is Your Love", cat: "oldies" },
  { artist: "Wham!", title: "Wake Me Up Before You Go-Go", cat: "oldies" },
  { artist: "Rick Astley", title: "Never Gonna Give You Up", cat: "oldies" },
  { artist: "Bonnie Tyler", title: "Total Eclipse of the Heart", cat: "oldies" },
  { artist: "Kim Wilde", title: "Cambodia", cat: "oldies" },
  { artist: "Sandra", title: "Maria Magdalena", cat: "oldies" },
  { artist: "Modern Talking", title: "Cheri, Cheri Lady", cat: "oldies" },
  { artist: "Opus", title: "Live Is Life", cat: "oldies" },
  { artist: "Falco", title: "Rock Me Amadeus", cat: "oldies" },
  { artist: "Nena", title: "99 Luftballons", cat: "oldies" },
  { artist: "Vanessa Paradis", title: "Marilyn & John", cat: "oldies" },
  { artist: "Jean-Jacques Goldman", title: "Il suffira d'un signe", cat: "oldies" },
  { artist: "Jean-Jacques Goldman", title: "Envole-moi", cat: "oldies" },
  { artist: "Michel Berger", title: "Le paradis blanc", cat: "oldies" },
  { artist: "France Gall", title: "Il jouait du piano debout", cat: "oldies" },
  { artist: "Alain Souchon", title: "Foule sentimentale", cat: "oldies" },
  { artist: "Laurent Voulzy", title: "Le cœur grenadine", cat: "oldies" },
  { artist: "Julien Clerc", title: "Ma préférence", cat: "oldies" },
  { artist: "Alain Bashung", title: "Osez Joséphine", cat: "oldies" },
  { artist: "Serge Gainsbourg", title: "La Javanaise", cat: "oldies" },
  { artist: "Boris Vian", title: "Le déserteur", cat: "oldies" },
  { artist: "Claude Nougaro", title: "Toulouse", cat: "oldies" },
  { artist: "Marc Lavoine", title: "Elle a les yeux revolver", cat: "oldies" },
  { artist: "Jeanne Mas", title: "En rouge et noir", cat: "oldies" },
  { artist: "Cookie Dingler", title: "Femme libérée", cat: "oldies" },
  { artist: "Philippe Lafontaine", title: "Cœur de loup", cat: "oldies" },
  { artist: "François Feldman", title: "Les valses de Vienne", cat: "oldies" },
  { artist: "Pauline Ester", title: "Oui je l'adore", cat: "oldies" },
  { artist: "Elsa", title: "T'en va pas", cat: "oldies" },
  { artist: "Patricia Kaas", title: "Mademoiselle chante le blues", cat: "oldies" },
];
