const NUMBERS = [
  { q: "En quelle année a été inaugurée la Tour Eiffel ?", a: 1889, unit: "", hint: "Exposition universelle de Paris" },
  { q: "En quelle année Christophe Colomb a-t-il découvert l'Amérique ?", a: 1492, unit: "", hint: "Les rois catholiques d'Espagne l'ont financé" },
  { q: "En quelle année la Révolution française a-t-elle commencé ?", a: 1789, unit: "", hint: "Prise de la Bastille" },
  { q: "En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?", a: 1969, unit: "", hint: "Mission Apollo 11" },
  { q: "En quelle année le mur de Berlin est-il tombé ?", a: 1989, unit: "", hint: "Fin de la guerre froide" },
  { q: "En quelle année Napoléon a-t-il été exilé à Sainte-Hélène ?", a: 1815, unit: "", hint: "Après Waterloo" },
  { q: "En quelle année Jules César a-t-il été assassiné ?", a: -44, unit: "", hint: "Aux ides de mars" },
  { q: "En quelle année a été signé le traité de Versailles ?", a: 1919, unit: "", hint: "Fin de la Première Guerre mondiale" },
  { q: "En quelle année Gutenberg a-t-il inventé l'imprimerie à caractères mobiles ?", a: 1450, unit: "", hint: "Vers le milieu du 15e siècle" },
  { q: "En quelle année la France a-t-elle aboli la peine de mort ?", a: 1981, unit: "", hint: "Sous le garde des sceaux Badinter" },
  { q: "En quelle année l'iPhone a-t-il été présenté pour la première fois ?", a: 2007, unit: "", hint: "Steve Jobs sur scène" },
  { q: "En quelle année Facebook a-t-il été fondé ?", a: 2004, unit: "", hint: "Dans un dortoir de Harvard" },
  { q: "En quelle année la Seconde Guerre mondiale a-t-elle pris fin ?", a: 1945, unit: "", hint: "Capitulation de l'Allemagne puis du Japon" },
  { q: "En quelle année l'Union soviétique s'est-elle dissoute ?", a: 1991, unit: "", hint: "Fin de la guerre froide" },
  { q: "En quelle année Christophe Colomb est-il né ?", a: 1451, unit: "", hint: "À Gênes, Italie" },
  { q: "En quelle année a été fondée la ville de Rome selon la légende ?", a: -753, unit: "", hint: "Par Romulus" },
  { q: "En quelle année a débuté la Première Guerre mondiale ?", a: 1914, unit: "", hint: "Assassinat de François-Ferdinand" },
  { q: "En quelle année a eu lieu le premier vol des frères Wright ?", a: 1903, unit: "", hint: "À Kitty Hawk, Caroline du Nord" },
  { q: "En quelle année Netflix a-t-il lancé son service de streaming ?", a: 2007, unit: "", hint: "Avant ça, c'était des DVD par courrier" },
  { q: "En quelle année l'accord de Paris sur le climat a-t-il été signé ?", a: 2015, unit: "", hint: "COP21" },
  { q: "Quelle est la hauteur de la Tour Eiffel en mètres (avec antenne) ?", a: 330, unit: "m", hint: "Plus haute que la Statue de la Liberté (93m)" },
  { q: "Quelle est la longueur du Nil en km ?", a: 6650, unit: "km", hint: "Le plus long fleuve du monde" },
  { q: "Quelle est la profondeur maximale de la fosse des Mariannes en mètres ?", a: 11000, unit: "m", hint: "Plus profond que l'Everest n'est haut" },
  { q: "Quelle est la distance de la Terre à la Lune en km ?", a: 384400, unit: "km", hint: "En moyenne, varie selon l'orbite" },
  { q: "Quelle est la longueur de la Grande Muraille de Chine en km ?", a: 21196, unit: "km", hint: "Avec toutes ses sections" },
  { q: "Quelle est la hauteur du Mont Everest en mètres ?", a: 8849, unit: "m", hint: "Le toit du monde" },
  { q: "Quelle est la superficie de la France métropolitaine en km² ?", a: 551000, unit: "km²", hint: "Environ la moitié de l'Alaska" },
  { q: "Quelle est la longueur de l'Amazone en km ?", a: 6400, unit: "km", hint: "Traverse l'Amérique du Sud" },
  { q: "Quelle est la distance Terre-Soleil en km ?", a: 149600000, unit: "km", hint: "1 unité astronomique" },
  { q: "Quelle est la vitesse de la lumière en km/s ?", a: 300000, unit: "km/s", hint: "Environ 3×10⁸ m/s" },
  { q: "Quelle est la longueur du Tunnel sous la Manche en km ?", a: 50, unit: "km", hint: "Relie Folkestone à Coquelles" },
  { q: "Quelle est la hauteur de la Statue de la Liberté en mètres (avec socle) ?", a: 93, unit: "m", hint: "Cadeau de la France aux États-Unis" },
  { q: "Quelle est la superficie du Brésil en km² ?", a: 8515767, unit: "km²", hint: "5e plus grand pays du monde" },
  { q: "Quelle est la longueur du Canal de Suez en km ?", a: 193, unit: "km", hint: "Relie la Méditerranée à la mer Rouge" },
  { q: "Quelle est la hauteur de la Burj Khalifa à Dubaï en mètres ?", a: 828, unit: "m", hint: "Plus haute tour du monde" },
  { q: "Quelle est la population mondiale approximative ?", a: 8100000000, unit: "habitants", hint: "Ça double tous les ~60 ans environ" },
  { q: "Quelle est la population de la France ?", a: 68000000, unit: "habitants", hint: "Environ 5e en Europe" },
  { q: "Quelle est la population de la Chine ?", a: 1400000000, unit: "habitants", hint: "Légèrement dépassée par l'Inde en 2023" },
  { q: "Quelle est la population de Paris intra-muros ?", a: 2100000, unit: "habitants", hint: "Grande couronne incluse : 12 millions" },
  { q: "Combien de pays composent l'Union européenne ?", a: 27, unit: "pays", hint: "Après le Brexit en 2020" },
  { q: "Combien de pays sont membres de l'ONU ?", a: 193, unit: "pays", hint: "Fondée en 1945 avec 51 membres" },
  { q: "Combien de fois Pelé a-t-il remporté la Coupe du Monde ?", a: 3, unit: "fois", hint: "1958, 1962, 1970" },
  { q: "Combien de Grand Chelem Rafael Nadal a-t-il remportés ?", a: 22, unit: "titres", hint: "Record avec Djokovic" },
  { q: "Combien de médailles d'or Michael Phelps a-t-il remportées aux JO ?", a: 23, unit: "médailles d'or", hint: "Plus grand olympien de l'histoire" },
  { q: "En quelle année la France a-t-elle remporté sa première Coupe du Monde de football ?", a: 1998, unit: "", hint: "À domicile, 3-0 contre le Brésil" },
  { q: "En combien de centièmes de seconde Usain Bolt a-t-il couru le 100m (record) ?", a: 958, unit: "centièmes", hint: "Usain Bolt en 2009 à Berlin" },
  { q: "Combien de fois le Real Madrid a-t-il remporté la Ligue des Champions ?", a: 15, unit: "fois", hint: "Record absolu" },
  { q: "En quelle année les premiers Jeux Olympiques modernes ont-ils eu lieu ?", a: 1896, unit: "", hint: "À Athènes" },
  { q: "Combien de joueurs composent une équipe de football sur le terrain ?", a: 11, unit: "joueurs", hint: "Idem au rugby à XV" },
  { q: "Combien de minutes dure le record du monde du marathon (arrondi) ?", a: 121, unit: "minutes", hint: "Kelvin Kiptum en 2023" },
  { q: "Combien d'os compte le corps humain adulte ?", a: 206, unit: "os", hint: "Plus que les bébés (270 à la naissance)" },
  { q: "Combien de chromosomes possède un être humain ?", a: 46, unit: "chromosomes", hint: "23 paires" },
  { q: "Quelle est la température du noyau de la Terre en degrés Celsius ?", a: 5500, unit: "°C", hint: "Aussi chaud que la surface du Soleil" },
  { q: "Combien de dents possède un adulte avec ses dents de sagesse ?", a: 32, unit: "dents", hint: "Sans sagesse : 28" },
  { q: "Quelle est la température d'ébullition de l'eau à pression normale ?", a: 100, unit: "°C", hint: "Moins en altitude" },
  { q: "Combien de planètes compte le système solaire ?", a: 8, unit: "planètes", hint: "Pluton déclassée en 2006" },
  { q: "Quelle est la durée d'une révolution de la Terre autour du Soleil en jours ?", a: 365, unit: "jours", hint: "365,25 exactement d'où les années bissextiles" },
  { q: "Combien d'éléments chimiques compte le tableau périodique ?", a: 118, unit: "éléments", hint: "Jusqu'à l'oganesson (Og)" },
  { q: "Quelles sont les 4 premiers chiffres de Pi (sans la virgule) ?", a: 3141, unit: "", hint: "3,141..." },
  { q: "Combien de litres de sang le cœur pompe-t-il par jour ?", a: 7200, unit: "litres", hint: "Environ 5L/min × 1440 minutes" },
  { q: "En quelle année a été peinte la Joconde par Léonard de Vinci ?", a: 1503, unit: "", hint: "Début du 16e siècle" },
  { q: "Combien de livres Harry Potter compte la saga principale ?", a: 7, unit: "livres", hint: "J.K. Rowling" },
  { q: "En quelle année a été fondée la ville de Paris (Lutèce) selon les historiens ?", a: -250, unit: "", hint: "Les Parisii, tribu gauloise" },
  { q: "Combien de marches compte la Tour Eiffel jusqu'au 2e étage ?", a: 674, unit: "marches", hint: "Accès piéton uniquement jusqu'au 2e" },
  { q: "Quelle est la longueur du Mississippi en km ?", a: 3730, unit: "km", hint: "Plus long fleuve des États-Unis" },
  { q: "Combien de tableaux Vincent van Gogh a-t-il peints au total ?", a: 900, unit: "tableaux", hint: "En seulement 10 ans de carrière" },
  { q: "En quelle année a été créé YouTube ?", a: 2005, unit: "", hint: "Racheté par Google l'année suivante" },
  { q: "Combien de pays partagent une frontière avec la France métropolitaine ?", a: 8, unit: "pays", hint: "Espagne, Andorre, Monaco, Italie, Suisse, Luxembourg, Allemagne, Belgique" },
  { q: "Quel est le numéro atomique de l'or ?", a: 79, unit: "", hint: "Symbole Au" },
  { q: "Combien de secondes y a-t-il dans une heure ?", a: 3600, unit: "secondes", hint: "60 × 60" },
  { q: "Combien de kilomètres de routes y a-t-il en France ?", a: 1000000, unit: "km", hint: "Le réseau routier le plus dense d'Europe" },
  { q: "En quelle année a été créé le réseau social Twitter ?", a: 2006, unit: "", hint: "Fondé par Jack Dorsey" },
  { q: "Quelle est la vitesse maximale d'un guépard en km/h ?", a: 120, unit: "km/h", hint: "L'animal terrestre le plus rapide" },
  { q: "Combien d'étages compte l'Empire State Building ?", a: 102, unit: "étages", hint: "New York, terminé en 1931" },
  { q: "En quelle année Titanic a-t-il coulé ?", a: 1912, unit: "", hint: "Lors de son voyage inaugural" },
  { q: "Combien de notes y a-t-il dans une gamme musicale occidentale ?", a: 7, unit: "notes", hint: "Do Ré Mi Fa Sol La Si" },
  { q: "Quelle est la superficie de la Russie en km² ?", a: 17100000, unit: "km²", hint: "Plus grand pays du monde" },
  { q: "En quelle année Minecraft a-t-il été officiellement lancé ?", a: 2011, unit: "", hint: "Créé par Markus Persson (Notch)" },
  { q: "Combien de Grammy Awards Beyoncé a-t-elle remportés (record absolu, 2024) ?", a: 32, unit: "Grammy", hint: "Record absolu tous artistes confondus" },
  { q: "En quelle année Airbus A380 a-t-il effectué son premier vol commercial ?", a: 2007, unit: "", hint: "Le plus grand avion de ligne du monde" },
  { q: "En quelle année Zinédine Zidane a-t-il donné son coup de tête lors de la finale du Mondial ?", a: 2006, unit: "", hint: "Finale France-Italie à Berlin" },
  { q: "Combien de titres de champion du monde de F1 Lewis Hamilton a-t-il remportés ?", a: 7, unit: "titres", hint: "Record absolu partagé avec Schumacher" },
  { q: "En quelle année Usain Bolt a-t-il établi son record du monde du 100m (9s58) ?", a: 2009, unit: "", hint: "Championnats du monde à Berlin" },
  { q: "Combien de fois la France a-t-elle remporté la Coupe Davis ?", a: 6, unit: "fois", hint: "Notamment 2017 et 2023" },
  { q: "Quel est le record de buts de Ronaldo en une saison de Liga ?", a: 50, unit: "buts", hint: "Saison 2011-2012 avec le Real Madrid" },
  { q: "Combien de mètres mesure un terrain de football officiel (longueur max) ?", a: 105, unit: "m", hint: "Largeur : 68m maximum" },
  { q: "En quelle année le PSG a-t-il été fondé ?", a: 1970, unit: "", hint: "Fusion de deux clubs parisiens" },
  { q: "Combien de points rapporte un essai au rugby à XV ?", a: 5, unit: "points", hint: "Plus la transformation : 7 au total" },
  { q: "Combien de sets faut-il gagner pour remporter une finale de Wimbledon messieurs ?", a: 3, unit: "sets", hint: "Format en 5 sets, 3 gagnants" },
  { q: "En quelle année Michael Jordan a-t-il remporté son 1er titre NBA ?", a: 1991, unit: "", hint: "Avec les Chicago Bulls" },
  { q: "Combien de km fait le Tour de France en moyenne ?", a: 3400, unit: "km", hint: "Varie chaque année, autour de 3 000-3 500" },
  { q: "En quelle année le premier iPhone a-t-il été commercialisé ?", a: 2007, unit: "", hint: "Présenté par Steve Jobs en janvier" },
  { q: "Combien de Mo fait un Go ?", a: 1024, unit: "Mo", hint: "En informatique binaire" },
  { q: "Quel est le numéro atomique du carbone ?", a: 6, unit: "", hint: "Base de toute vie organique" },
  { q: "En quelle année le génome humain a-t-il été entièrement séquencé ?", a: 2003, unit: "", hint: "Projet Génome Humain" },
  { q: "Combien de satellites naturels possède Mars ?", a: 2, unit: "lunes", hint: "Phobos et Déimos" },
  { q: "Quelle est la température moyenne à la surface de Mars en °C ?", a: -60, unit: "°C", hint: "Entre -125°C et +20°C selon la saison" },
  { q: "En quelle année le premier ordinateur personnel grand public (Apple II) est-il sorti ?", a: 1977, unit: "", hint: "Fondateurs : Steve Jobs et Steve Wozniak" },
  { q: "Combien de régions administratives compte la France métropolitaine ?", a: 13, unit: "régions", hint: "Depuis la réforme de 2016" },
  { q: "Quelle est la longueur des côtes françaises métropolitaines en km ?", a: 5800, unit: "km", hint: "Atlantique + Méditerranée + Manche" },
  { q: "Quelle est la superficie de l'Antarctique en km² ?", a: 14000000, unit: "km²", hint: "Couvert à 98% de glace" },
  { q: "À quelle altitude se trouve le Col du Mont-Blanc (tunnel routier) ?", a: 1381, unit: "m", hint: "L'entrée côté France à Chamonix" },
  { q: "Combien de départements compte la France (métropole + outre-mer) ?", a: 101, unit: "départements", hint: "95 métropolitains + 6 d'outre-mer" },
  { q: "En quelle année la Déclaration des droits de l'homme et du citoyen a-t-elle été adoptée ?", a: 1789, unit: "", hint: "Même année que la Révolution" },
  { q: "Combien d'années a duré le règne de Louis XIV ?", a: 72, unit: "ans", hint: "Plus long règne de l'histoire de France" },
  { q: "En quelle année l'Allemagne a-t-elle été réunifiée ?", a: 1990, unit: "", hint: "Un an après la chute du Mur de Berlin" },
  { q: "Combien d'États américains composent les États-Unis ?", a: 50, unit: "États", hint: "Hawaii et Alaska ont rejoint en 1959" },
  { q: "En quelle année l'Algérie a-t-elle obtenu son indépendance ?", a: 1962, unit: "", hint: "Accords d'Évian" },
  { q: "En quelle année Napoléon est-il né ?", a: 1769, unit: "", hint: "À Ajaccio, en Corse" },
  { q: "Combien de saisons compte la série Game of Thrones ?", a: 8, unit: "saisons", hint: "La 8ème a été très controversée" },
  { q: "En quelle année est sorti le film Avatar de James Cameron ?", a: 2009, unit: "", hint: "Film le plus rentable de l'histoire (longtemps)" },
  { q: "Combien de films compte la saga Star Wars (films principaux) ?", a: 9, unit: "films", hint: "Sans les spin-offs" },
  { q: "Combien de caractères maximum permettait Twitter à l'origine ?", a: 140, unit: "caractères", hint: "Doublé à 280 en 2017" },
  { q: "En quelle année Spotify a-t-il été lancé ?", a: 2008, unit: "", hint: "Fondé en Suède par Daniel Ek" },
  { q: "Combien d'albums studio les Beatles ont-ils enregistrés ?", a: 13, unit: "albums", hint: "De Please Please Me à Let It Be" },
  { q: "En quelle année le film Titanic de James Cameron est-il sorti ?", a: 1997, unit: "", hint: "11 Oscars dont meilleur film" },
  { q: "Combien de langues sont actuellement reconnues comme langues officielles à l'ONU ?", a: 6, unit: "langues", hint: "Anglais, français, arabe, chinois, russe, espagnol" },
  { q: "Combien d'abonnés possède la chaîne YouTube la plus suivie (T-Series) ?", a: 270000000, unit: "abonnés", hint: "Chaîne de Bollywood indienne" },
  { q: "En quelle année Michael Jackson est-il décédé ?", a: 2009, unit: "" },
  { q: "Combien de kilomètres sépare Paris de New York à vol d'oiseau ?", a: 5837, unit: "km" },
  { q: "Combien y a-t-il de touches sur un piano standard ?", a: 88, unit: "touches" },
  { q: "En quelle année la Game Boy est-elle sortie en Europe ?", a: 1990, unit: "" },
  { q: "Combien de joueurs composent une équipe de rugby à XV sur le terrain ?", a: 15, unit: "joueurs" },
  { q: "Combien de départements compte la France (métropole + outre-mer) ?", a: 101, unit: "départements" },
  { q: "En quelle année a eu lieu la catastrophe de Tchernobyl ?", a: 1986, unit: "" },
  { q: "Combien de dents possède un adulte (dents de sagesse comprises) ?", a: 32, unit: "dents" },
  { q: "Quelle est la profondeur maximale de la fosse des Mariannes en mètres ?", a: 10984, unit: "m" },
  { q: "Combien d'étoiles figurent sur le drapeau américain ?", a: 50, unit: "étoiles" },
  { q: "En quelle année le premier iPhone est-il sorti ?", a: 2007, unit: "" },
  { q: "Combien de cases y a-t-il sur un échiquier ?", a: 64, unit: "cases" },
  { q: "Combien de minutes dure un match de football (temps réglementaire) ?", a: 90, unit: "minutes" },
  { q: "En quelle année Zinédine Zidane a-t-il mis son coup de boule à Materazzi ?", a: 2006, unit: "" },
  { q: "Combien de pays partagent une frontière terrestre avec la France métropolitaine ?", a: 8, unit: "pays" },
  { q: "Quelle est la vitesse maximale d'un guépard en km/h ?", a: 110, unit: "km/h" },
  { q: "Combien y a-t-il de zéros dans un milliard ?", a: 9, unit: "zéros" },
  { q: "En quelle année Facebook a-t-il été créé ?", a: 2004, unit: "" },
  { q: "Combien de côtés a un hendécagone ?", a: 11, unit: "côtés" },
  { q: "Combien de temps met la lumière du Soleil pour atteindre la Terre en minutes ?", a: 8, unit: "minutes" },
  { q: "En quelle année la Coupe du monde a-t-elle eu lieu au Qatar ?", a: 2022, unit: "" },
  { q: "Combien de films Harry Potter existe-t-il ?", a: 8, unit: "films" },
  { q: "Combien de saisons compte la série Game of Thrones ?", a: 8, unit: "saisons" },
  { q: "En quelle année est sorti le premier film Star Wars ?", a: 1977, unit: "" },
  { q: "Combien pèse un ballon de football en grammes (environ) ?", a: 430, unit: "g" },
  { q: "Combien de Grammy Awards Beyoncé a-t-elle remportés (record) ?", a: 32, unit: "Grammys" },
  { q: "En quelle année Nirvana a-t-il sorti Nevermind ?", a: 1991, unit: "" },
  { q: "Combien de cordes possède une guitare classique ?", a: 6, unit: "cordes" },
  { q: "Combien de albums studio a sorti Jul (environ, fin 2024) ?", a: 34, unit: "albums" },
  { q: "En quelle année Stromae a-t-il sorti Alors on danse ?", a: 2009, unit: "" },
  { q: "Combien de spectateurs peut accueillir le Stade de France ?", a: 80698, unit: "places" },
  { q: "Combien de km fait le tour de la Terre à l'équateur ?", a: 40075, unit: "km" },
  { q: "Combien y a-t-il de secondes dans une journée ?", a: 86400, unit: "secondes" },
  { q: "En quelle année est né Kylian Mbappé ?", a: 1998, unit: "" },
  { q: "Combien de Ballons d'Or Lionel Messi a-t-il remportés ?", a: 8, unit: "Ballons d'Or" },
  { q: "Combien de titres de champion du monde de F1 a Lewis Hamilton ?", a: 7, unit: "titres" },
  { q: "Combien de km/h fait la vitesse du son (environ) ?", a: 1224, unit: "km/h" },
  { q: "En quelle année la Réunion est-elle devenue un département français ?", a: 1946, unit: "" },
  { q: "Combien d'épisodes compte la série Friends ?", a: 236, unit: "épisodes" },
  { q: "Combien de lettres compte l'alphabet grec ?", a: 24, unit: "lettres" },
  { q: "En quelle année a été inventé le World Wide Web ?", a: 1989, unit: "" },
  { q: "Combien de communes compte la France (environ) ?", a: 34955, unit: "communes" },
  { q: "Quelle est la hauteur du Mont Blanc en mètres ?", a: 4806, unit: "m" },
  { q: "Combien de calories dans un Big Mac ?", a: 550, unit: "kcal" },
  { q: "En quelle année GTA V est-il sorti ?", a: 2013, unit: "" },
  { q: "Combien d'or (en tonnes) détient la Banque de France (environ) ?", a: 2436, unit: "tonnes" },
  { q: "Combien de marches pour monter au sommet de la tour Eiffel ?", a: 1665, unit: "marches" },
  { q: "Combien de joueurs simultanés maximum dans une partie de Fortnite Battle Royale ?", a: 100, unit: "joueurs" },
  { q: "En quelle année Daft Punk s'est-il séparé ?", a: 2021, unit: "" },
  { q: "Combien de pattes possède une araignée ?", a: 8, unit: "pattes" },
  { q: "Combien de km sépare la Terre de la Lune (en moyenne) ?", a: 384400, unit: "km", hint: "Un peu plus d'un tiers de million" },
  { q: "En quelle année est sorti le premier Harry Potter (livre) ?", a: 1997, unit: "", hint: "Années 1990" },
  { q: "Combien d'habitants compte Marseille ?", a: 870000, unit: "habitants", hint: "Deuxième ville de France" },
  { q: "Combien d'habitants compte Tokyo (agglomération) ?", a: 37000000, unit: "habitants", hint: "La plus grande agglomération du monde" },
  { q: "Combien de km fait la Muraille de Chine (tous tronçons) ?", a: 21196, unit: "km", hint: "Plus de 20 000" },
  { q: "En quelle année a été prise la Bastille ?", a: 1789, unit: "", hint: "Début de la Révolution" },
  { q: "Combien pèse un éléphant d'Afrique adulte (mâle) en kg ?", a: 6000, unit: "kg", hint: "Plusieurs tonnes" },
  { q: "Combien de battements par minute fait un cœur humain au repos ?", a: 70, unit: "bpm", hint: "Entre 60 et 100" },
  { q: "Combien y a-t-il d'os dans le corps humain adulte ?", a: 206, unit: "os", hint: "Un bébé en a plus de 300" },
  { q: "En quelle année l'homme a-t-il marché sur la Lune ?", a: 1969, unit: "", hint: "Fin des années 60" },
  { q: "Combien de km/h atteint une balle de tennis au service (record) ?", a: 263, unit: "km/h", hint: "Record de Sam Groth" },
  { q: "Combien d'étoiles compte le drapeau européen ?", a: 12, unit: "étoiles", hint: "Ce n'est pas le nombre de pays" },
  { q: "Combien de pays membres compte l'Union européenne ?", a: 27, unit: "pays", hint: "Depuis le Brexit" },
  { q: "Combien de langues officielles compte l'Inde ?", a: 22, unit: "langues", hint: "Plus de 20" },
  { q: "Combien coûte une baguette de pain en moyenne en France (en centimes) ?", a: 110, unit: "centimes", hint: "Environ 1 euro" },
  { q: "Combien de McDonald's y a-t-il en France ?", a: 1560, unit: "restaurants", hint: "2e marché mondial" },
  { q: "Combien de tours compte la cathédrale Notre-Dame de Paris ?", a: 2, unit: "tours", hint: "Facile si tu l'as vue" },
  { q: "En quelle année a été inauguré la tour Eiffel ?", a: 1889, unit: "", hint: "Exposition universelle" },
  { q: "Combien de mètres mesure la tour Eiffel (avec antennes) ?", a: 330, unit: "m", hint: "Plus de 300" },
  { q: "Combien de km parcourt le Tour de France (environ) ?", a: 3500, unit: "km", hint: "Plus de 3 000" },
  { q: "Combien de joueurs y a-t-il sur un terrain de volley (par équipe) ?", a: 6, unit: "joueurs", hint: "Moins de 10" },
  { q: "Combien de médailles d'or Michael Phelps a-t-il remportées aux JO ?", a: 23, unit: "médailles", hint: "Record absolu" },
  { q: "Combien de cartes compte un jeu de tarot ?", a: 78, unit: "cartes", hint: "Plus qu'un jeu de 54" },
  { q: "Combien de cases noires compte un damier de dames (10x10) ?", a: 50, unit: "cases", hint: "La moitié du damier" },
  { q: "En quelle année Google a-t-il été fondé ?", a: 1998, unit: "", hint: "Fin des années 90" },
  { q: "En quelle année YouTube a-t-il été créé ?", a: 2005, unit: "", hint: "Milieu des années 2000" },
  { q: "Combien de followers a le compte Instagram le plus suivi (Ronaldo) en millions ?", a: 640, unit: "millions", hint: "Plus d'un demi-milliard" },
  { q: "Combien d'heures de vidéo sont uploadées sur YouTube chaque minute ?", a: 500, unit: "heures", hint: "Plusieurs centaines" },
  { q: "Combien de pizzas sont consommées en France par seconde ?", a: 26, unit: "pizzas", hint: "Plus de 20" },
  { q: "Combien de litres d'eau faut-il pour produire 1 kg de bœuf ?", a: 15000, unit: "litres", hint: "Plus de 10 000" },
  { q: "Combien de croissants un Français mange-t-il par an en moyenne ?", a: 30, unit: "croissants", hint: "Moins d'un par semaine" },
  { q: "Quelle est la profondeur moyenne des océans en mètres ?", a: 3700, unit: "m", hint: "Plusieurs km" },
  { q: "Combien d'espèces d'insectes sont décrites dans le monde ?", a: 1000000, unit: "espèces", hint: "Environ un million" },
  { q: "Combien d'années vit une tortue géante des Galapagos ?", a: 150, unit: "ans", hint: "Plus de 100" },
  { q: "Combien de dents a un requin blanc (en fonction) ?", a: 50, unit: "dents", hint: "Sur plusieurs rangées : 300 au total" },
  { q: "Combien de kg de nourriture un panda mange-t-il par jour ?", a: 20, unit: "kg", hint: "Que du bambou ou presque" },
  { q: "En quelle année est sorti le premier épisode des Simpson ?", a: 1989, unit: "", hint: "Fin des années 80" },
  { q: "Combien d'épisodes compte One Piece (anime, environ) ?", a: 1100, unit: "épisodes", hint: "Plus de 1 000" },
  { q: "Combien de films Marvel (MCU) sont sortis au cinéma (2024) ?", a: 34, unit: "films", hint: "Plus de 30" },
  { q: "Combien a coûté le film Avatar (2009) en millions de dollars ?", a: 237, unit: "millions $", hint: "Plus de 200" },
  { q: "Combien de répliques de la statue de la Liberté y a-t-il à Paris ?", a: 5, unit: "répliques", hint: "Moins de 10" },
  { q: "Combien de ponts traversent la Seine à Paris ?", a: 37, unit: "ponts", hint: "Plus de 30" },
  { q: "Combien de stations compte le métro parisien ?", a: 308, unit: "stations", hint: "Plus de 300" },
  { q: "Combien de départements portent un nom de fleuve ou rivière ?", a: 68, unit: "départements", hint: "Plus de la moitié" },
  { q: "En quelle année la Corse est-elle devenue française ?", a: 1768, unit: "", hint: "Un an avant la naissance de Napoléon" },
  { q: "Combien de calories brûle-t-on en dormant 8 heures ?", a: 500, unit: "kcal", hint: "Environ 60 par heure" },
  { q: "Combien de fois par jour un adulte cligne-t-il des yeux ?", a: 15000, unit: "fois", hint: "Plus de 10 000" },
  { q: "Combien de litres de salive produit-on par jour ?", a: 1, unit: "litre", hint: "Entre 0,5 et 1,5" },
  { q: "Combien de kilomètres de vaisseaux sanguins contient le corps humain ?", a: 100000, unit: "km", hint: "Plus de 2 fois le tour de la Terre" },
  { q: "Combien de respirations prend-on par jour ?", a: 20000, unit: "respirations", hint: "Plus de 15 000" },
  { q: "En quelle année Netflix a-t-il lancé le streaming ?", a: 2007, unit: "" },
  { q: "Combien de pays y a-t-il en Afrique ?", a: 54, unit: "pays" },
  { q: "Combien d'îles compte la Grèce (environ) ?", a: 6000, unit: "îles" },
  { q: "Combien de temps un vol Paris-New York dure-t-il en minutes ?", a: 480, unit: "minutes" },
  { q: "Combien de personnes ont marché sur la Lune ?", a: 12, unit: "personnes" },
  { q: "En quelle année est mort Napoléon ?", a: 1821, unit: "" },
  { q: "Combien de femmes ont été Première ministre en France ?", a: 2, unit: "femmes" },
  { q: "Combien de présidents a eu la Ve République (2024) ?", a: 8, unit: "présidents" },
  { q: "Combien d'habitants compte Monaco ?", a: 38000, unit: "habitants" },
  { q: "Combien de km² fait Monaco ?", a: 2, unit: "km²" },
  { q: "Combien de marches compte la butte Montmartre (escalier principal) ?", a: 222, unit: "marches" },
  { q: "Combien de visiteurs le Louvre accueille-t-il par an (millions) ?", a: 9, unit: "millions" },
  { q: "Combien d'œuvres sont exposées au Louvre ?", a: 35000, unit: "œuvres" },
  { q: "En quelle année a été peinte la Joconde (environ) ?", a: 1503, unit: "" },
  { q: "Combien de kg pèse la cloche Emmanuel de Notre-Dame ?", a: 13000, unit: "kg" },
  { q: "Combien de fromages différents existe-t-il en France (environ) ?", a: 1200, unit: "fromages" },
  { q: "Combien de baguettes sont vendues chaque jour en France (millions) ?", a: 12, unit: "millions" },
  { q: "Combien de bouteilles de champagne sont vendues par an dans le monde (millions) ?", a: 300, unit: "millions" },
  { q: "Combien de grains de riz y a-t-il dans un kilo (environ) ?", a: 50000, unit: "grains" },
  { q: "Combien de tasses de café sont bues chaque jour dans le monde (milliards) ?", a: 2, unit: "milliards" },
  { q: "Quelle est la température au centre de la Terre en °C ?", a: 5500, unit: "°C" },
  { q: "Combien d'éclairs frappent la Terre chaque seconde ?", a: 100, unit: "éclairs" },
  { q: "Combien de tremblements de terre sont détectés par an dans le monde ?", a: 500000, unit: "séismes" },
  { q: "Quelle est la hauteur des chutes du Niagara en mètres ?", a: 57, unit: "m" },
  { q: "Quelle est la longueur de l'Amazone en km ?", a: 6400, unit: "km" },
  { q: "Combien d'arbres y a-t-il sur Terre (milliards) ?", a: 3000, unit: "milliards" },
  { q: "Quelle est la vitesse de croisière d'un avion de ligne en km/h ?", a: 900, unit: "km/h" },
  { q: "Combien d'avions volent en même temps dans le monde (en moyenne) ?", a: 10000, unit: "avions" },
  { q: "Combien de voitures sont produites par an dans le monde (millions) ?", a: 90, unit: "millions" },
  { q: "Quelle est la vitesse maximale du TGV en service en km/h ?", a: 320, unit: "km/h" },
  { q: "En quelle année le premier TGV est-il entré en service ?", a: 1981, unit: "" },
  { q: "Combien de gares compte la France (environ) ?", a: 3000, unit: "gares" },
  { q: "Combien de kilomètres d'autoroutes compte la France ?", a: 11700, unit: "km" },
  { q: "Combien de ronds-points y a-t-il en France ?", a: 65000, unit: "ronds-points" },
  { q: "Combien coûte une Bugatti Chiron en millions d'euros ?", a: 3, unit: "millions €" },
  { q: "Combien de Lego sont vendus chaque seconde dans le monde ?", a: 1300, unit: "briques" },
  { q: "Combien de Big Mac sont vendus par seconde dans le monde ?", a: 17, unit: "Big Mac" },
  { q: "Combien de photos sont postées sur Instagram par jour (millions) ?", a: 95, unit: "millions" },
  { q: "Combien de recherches Google sont faites par seconde ?", a: 99000, unit: "recherches" },
  { q: "Combien de mails sont envoyés par jour dans le monde (milliards) ?", a: 350, unit: "milliards" },
  { q: "Combien de sites web existent dans le monde (milliards) ?", a: 2, unit: "milliards" },
  { q: "En quelle année a été envoyé le premier SMS ?", a: 1992, unit: "" },
  { q: "En quelle année a été créé Wikipédia ?", a: 2001, unit: "" },
  { q: "Combien d'articles compte Wikipédia en français (millions) ?", a: 2, unit: "millions" },
  { q: "Combien de mots compte la langue française (dictionnaires cumulés) ?", a: 100000, unit: "mots" },
  { q: "Combien de lettres compte le mot le plus long du dictionnaire français ?", a: 25, unit: "lettres" },
  { q: "Combien de pays parlent officiellement le français ?", a: 29, unit: "pays" },
  { q: "Combien de francophones y a-t-il dans le monde (millions) ?", a: 320, unit: "millions" },
  { q: "Combien de temps un escargot met-il pour parcourir 1 km (en heures) ?", a: 21, unit: "heures" },
  { q: "Combien d'années vit un chêne (en moyenne) ?", a: 500, unit: "ans" },
  { q: "Combien de cœurs possède une pieuvre ?", a: 3, unit: "cœurs" },
  { q: "Combien d'estomacs possède une vache ?", a: 4, unit: "estomacs" },
  { q: "Combien d'yeux possède une abeille ?", a: 5, unit: "yeux" },
  { q: "Combien de muscles utilise-t-on pour sourire ?", a: 17, unit: "muscles" },
  { q: "Combien de fois le cœur bat-il en une vie (milliards) ?", a: 3, unit: "milliards" },
  { q: "Combien de cheveux avons-nous sur la tête ?", a: 100000, unit: "cheveux" },
  { q: "Combien de neurones compte le cerveau humain (milliards) ?", a: 86, unit: "milliards" },
  { q: "Combien de rêves fait-on par nuit en moyenne ?", a: 5, unit: "rêves" },
  { q: "Combien de litres de sang le cœur pompe-t-il par jour ?", a: 7500, unit: "litres" },
  { q: "Quelle est la longueur de l'intestin grêle en mètres ?", a: 6, unit: "m" },
  { q: "En quelle année sont nés les jeux Pokémon (Game Boy) ?", a: 1996, unit: "" },
  { q: "Combien de Pokémon existe-t-il (2024) ?", a: 1025, unit: "Pokémon" },
  { q: "Combien d'exemplaires GTA V s'est-il vendu (millions) ?", a: 200, unit: "millions" },
  { q: "Combien d'exemplaires Minecraft s'est-il vendu (millions) ?", a: 300, unit: "millions" },
  { q: "En quelle année est sorti Fortnite Battle Royale ?", a: 2017, unit: "" },
  { q: "Combien de joueurs compte League of Legends par mois (millions) ?", a: 130, unit: "millions" },
  { q: "En quelle année est sortie la PlayStation 1 en Europe ?", a: 1995, unit: "" },
  { q: "Combien de PS2 ont été vendues (millions, record console) ?", a: 160, unit: "millions" },
  { q: "Combien de manettes N64 fallait-il pour Mario Kart à 4 ?", a: 4, unit: "manettes" },
  { q: "Combien de films Fast and Furious sont sortis (2024) ?", a: 11, unit: "films" },
  { q: "Combien de James Bond officiels existent (films, 2024) ?", a: 25, unit: "films" },
  { q: "Combien d'acteurs ont incarné James Bond au cinéma (officiellement) ?", a: 6, unit: "acteurs" },
  { q: "Combien d'Oscars Titanic a-t-il remportés ?", a: 11, unit: "Oscars" },
  { q: "Combien de saisons compte Grey's Anatomy (2024) ?", a: 20, unit: "saisons" },
  { q: "Combien d'épisodes compte Naruto + Shippuden ?", a: 720, unit: "épisodes" },
  { q: "Combien de tomes compte le manga One Piece (2024) ?", a: 108, unit: "tomes" },
  { q: "Combien d'exemplaires One Piece s'est-il vendu (millions) ?", a: 520, unit: "millions" },
  { q: "En quelle année est sorti le premier Star Wars ?", a: 1977, unit: "" },
  { q: "Combien a rapporté Avengers Endgame au box-office (milliards $) ?", a: 2.8, unit: "milliards $" },
  { q: "Combien de langues Harry Potter a-t-il été traduit ?", a: 85, unit: "langues" },
  { q: "Combien de pages compte Harry Potter et l'Ordre du Phénix (VF) ?", a: 980, unit: "pages" },
  { q: "Combien de spectateurs Intouchables a-t-il fait en France (millions) ?", a: 19, unit: "millions" },
  { q: "Quel est le record de spectateurs pour un film en France (millions, Titanic) ?", a: 22, unit: "millions" },
  { q: "Combien de Molières Bienvenue chez les Ch'tis a-t-il fait d'entrées (millions) ?", a: 20, unit: "millions" },
  { q: "Combien de km court-on dans un match de foot (joueur de champ) ?", a: 10, unit: "km" },
  { q: "Combien de ballons sont utilisés pendant un match de tennis du Grand Chelem ?", a: 60000, unit: "balles" },
  { q: "Combien de calories brûle un cycliste sur une étape du Tour ?", a: 6000, unit: "kcal" },
  { q: "Combien de spectateurs peut accueillir le Camp Nou (rénové) ?", a: 105000, unit: "places" },
  { q: "Combien de titres de Grand Chelem a Novak Djokovic (2024) ?", a: 24, unit: "titres" },
  { q: "Combien de buts Pelé a-t-il marqués dans sa carrière (officiel) ?", a: 767, unit: "buts" },
  { q: "Combien de sélections compte Hugo Lloris en équipe de France ?", a: 145, unit: "sélections" },
  { q: "Combien de Coupes du monde l'équipe de France a-t-elle gagnées ?", a: 2, unit: "Coupes" },
  { q: "En quelle année la France a-t-elle gagné sa première Coupe du monde ?", a: 1998, unit: "" },
  { q: "Combien de joueurs NBA mesurent plus de 2m20 (2024) ?", a: 4, unit: "joueurs" },
  { q: "Combien de points Wilt Chamberlain a-t-il marqués dans son match record ?", a: 100, unit: "points" },
  { q: "Combien de médailles la France a-t-elle remportées aux JO de Paris 2024 ?", a: 64, unit: "médailles" },
  { q: "Combien de fois une personne rit-elle par jour en moyenne ?", a: 17, unit: "fois" },
  { q: "Combien de pets une personne fait-elle par jour en moyenne ?", a: 15, unit: "pets" },
  { q: "Combien de litres de salive produit-on dans toute une vie ?", a: 25000, unit: "litres" },
  { q: "Combien de fois cligne-t-on des yeux dans une vie (milliards) ?", a: 415, unit: "millions" },
  { q: "Combien de kilos de peau perd-on dans une vie ?", a: 35, unit: "kg" },
  { q: "Combien de temps passe-t-on à dormir dans une vie (années) ?", a: 26, unit: "ans" },
  { q: "Combien de temps passe-t-on aux toilettes dans une vie (jours) ?", a: 92, unit: "jours" },
  { q: "Combien de kilomètres marche-t-on dans une vie (tour de la Terre) ?", a: 4, unit: "fois le tour" },
  { q: "Combien de bactéries vivent dans la bouche humaine (milliards) ?", a: 20, unit: "milliards" },
  { q: "Combien pèsent toutes les fourmis de la Terre vs les humains (ratio) ?", a: 1, unit: "pour 1" },
  { q: "Combien de fourmis y a-t-il sur Terre (millions de milliards) ?", a: 20, unit: "millions de milliards" },
  { q: "Combien de temps un poulet a-t-il vécu sans tête (record, jours) ?", a: 547, unit: "jours" },
  { q: "Combien de dents pousse un requin dans sa vie ?", a: 30000, unit: "dents" },
  { q: "Combien de temps dort un koala par jour (heures) ?", a: 22, unit: "heures" },
  { q: "Combien de temps dort une girafe par jour (heures) ?", a: 2, unit: "heures" },
  { q: "Combien de km une hirondelle parcourt-elle en migration ?", a: 11000, unit: "km" },
  { q: "Combien de battements par seconde fait le cœur d'un colibri ?", a: 20, unit: "battements" },
  { q: "Combien de temps un escargot peut-il dormir (années) ?", a: 3, unit: "ans" },
  { q: "Combien pèse la langue d'une baleine bleue (kg) ?", a: 2700, unit: "kg" },
  { q: "Combien de litres de lait une vache produit-elle par jour ?", a: 28, unit: "litres" },
  { q: "Combien d'œufs une poule pond-elle par an ?", a: 300, unit: "œufs" },
  { q: "Combien de temps un caméléon peut-il bouger ses yeux indépendamment (angle) ?", a: 360, unit: "degrés" },
  { q: "Combien de temps un ours hiberne-t-il (mois) ?", a: 6, unit: "mois" },
  { q: "Combien de piquants a un hérisson (environ) ?", a: 6000, unit: "piquants" },
  { q: "Combien de temps une tortue peut-elle retenir sa respiration (heures) ?", a: 7, unit: "heures" },
  { q: "À quelle vitesse pousse un cheveu par mois (cm) ?", a: 1, unit: "cm" },
  { q: "Combien de temps met un ongle de main pour repousser entièrement (mois) ?", a: 6, unit: "mois" },
  { q: "Combien de bananes un humain devrait manger pour une dose mortelle de potassium ?", a: 400, unit: "bananes" },
  { q: "Combien de canettes de soda faudrait-il pour flotter (personne moyenne) ?", a: 450, unit: "canettes" },
  { q: "Combien de ballons d'hélium faut-il pour soulever une personne ?", a: 5000, unit: "ballons" },
  { q: "Combien de temps la lumière du Soleil met pour atteindre Pluton (heures) ?", a: 5, unit: "heures" },
  { q: "Combien de fois la Lune tiendrait entre la Terre et le Soleil ?", a: 400, unit: "fois" },
  { q: "Combien pèserait un humain de 70 kg sur la Lune (kg) ?", a: 12, unit: "kg" },
  { q: "Combien d'étoiles peut-on voir à l'œil nu par nuit claire ?", a: 2500, unit: "étoiles" },
  { q: "Combien de galaxies l'univers observable contient-il (milliards) ?", a: 2000, unit: "milliards" },
  { q: "Combien de temps faudrait-il pour aller à la station spatiale en voiture (jours) ?", a: 1, unit: "jour" },
  { q: "À quelle altitude vole la Station spatiale internationale (km) ?", a: 400, unit: "km" },
  { q: "Combien de fois l'ISS fait-elle le tour de la Terre par jour ?", a: 16, unit: "fois" },
  { q: "Combien coûte un aller simple vers Mars par SpaceX (objectif, milliers $) ?", a: 500, unit: "milliers $" },
  { q: "Combien de diamants pleuvent-ils sur Neptune et Uranus (théorie, carats) ?", a: 1000000, unit: "carats" },
  { q: "Combien pèse un nuage moyen (tonnes) ?", a: 500, unit: "tonnes" },
  { q: "Combien de gouttes d'eau y a-t-il dans un nuage d'orage (milliards) ?", a: 1000, unit: "milliards" },
  { q: "Quelle est la vitesse d'une goutte de pluie qui tombe (km/h) ?", a: 30, unit: "km/h" },
  { q: "Combien de foudre frappe la tour Eiffel par an ?", a: 5, unit: "fois" },
  { q: "Quelle est la température d'un éclair (°C) ?", a: 30000, unit: "°C" },
  { q: "Combien de temps met un flocon de neige pour tomber (minutes) ?", a: 60, unit: "minutes" },
  { q: "Combien de côtés a un flocon de neige (symétrie) ?", a: 6, unit: "côtés" },
  { q: "Combien de litres d'eau y a-t-il dans le corps humain adulte ?", a: 42, unit: "litres" },
  { q: "Combien de temps peut-on survivre sans eau (jours) ?", a: 3, unit: "jours" },
  { q: "Combien de temps peut-on survivre sans dormir (record, jours) ?", a: 11, unit: "jours" },
  { q: "À quelle vitesse voyage un éternuement (km/h) ?", a: 160, unit: "km/h" },
  { q: "À quelle vitesse une information voyage dans les nerfs (km/h) ?", a: 430, unit: "km/h" },
  { q: "Combien de fois par jour regarde-t-on son téléphone (moyenne) ?", a: 150, unit: "fois" },
  { q: "Combien de temps par jour passe-t-on sur son téléphone (heures) ?", a: 4, unit: "heures" },
  { q: "Combien de mots de passe une personne a-t-elle en moyenne ?", a: 100, unit: "mots de passe" },
  { q: "Combien d'applications compte l'App Store (millions) ?", a: 2, unit: "millions" },
  { q: "Combien de vidéos YouTube sont regardées par jour (milliards) ?", a: 5, unit: "milliards" },
  { q: "Combien de likes sont donnés sur Instagram par jour (milliards) ?", a: 4, unit: "milliards" },
  { q: "Combien de tweets sont postés par seconde ?", a: 6000, unit: "tweets" },
  { q: "Combien d'émojis existe-t-il (2024) ?", a: 3782, unit: "émojis" },
  { q: "Quel est l'émoji le plus utilisé au monde (rang du 😂) ?", a: 1, unit: "" },
  { q: "Combien de langues sont parlées dans le monde ?", a: 7000, unit: "langues" },
  { q: "Combien de nouveaux-nés naissent chaque seconde dans le monde ?", a: 4, unit: "bébés" },
  { q: "Combien de personnes sont nées le même jour que vous (millions) ?", a: 20, unit: "millions" },
  { q: "Combien de cellules le corps humain contient-il (milliers de milliards) ?", a: 37, unit: "milliers de milliards" },
  { q: "Combien de fois plie-t-on une feuille pour atteindre la Lune (théorie) ?", a: 42, unit: "fois" },
  { q: "Combien de grains de sable y a-t-il sur toutes les plages (chiffre à zéros) ?", a: 19, unit: "zéros" },
  { q: "Combien de temps a duré la plus courte guerre de l'histoire (minutes) ?", a: 38, unit: "minutes" },
  { q: "Combien pèse l'objet le plus lourd jamais soulevé par l'homme (tonnes) ?", a: 13300, unit: "tonnes" },
  { q: "Combien de langues Cléopâtre parlait-elle ?", a: 9, unit: "langues" },
  { q: "Quel âge avait la plus jeune personne à gravir l'Everest (ans) ?", a: 13, unit: "ans" },
  { q: "Combien de temps a vécu la personne la plus âgée (ans) ?", a: 122, unit: "ans" },
  { q: "Combien de fois le mot 'amour' apparaît dans les chansons (top hits, %) ?", a: 60, unit: "%" },
  { q: "Combien de bulles y a-t-il dans une flûte de champagne ?", a: 1000000, unit: "bulles" },
  { q: "Combien de temps met le ketchup pour sortir de la bouteille (km/h) ?", a: 1, unit: "km/h" },
  { q: "Combien de fèves de cacao faut-il pour 1 kg de chocolat ?", a: 400, unit: "fèves" },
  { q: "Combien de temps se conserve le miel (années) ?", a: 3000, unit: "ans" },
  { q: "Combien de pizzas Margherita sont mangées par jour en Italie (millions) ?", a: 5, unit: "millions" },
  { q: "Combien de croissants sont vendus par jour à Paris (millions) ?", a: 2, unit: "millions" },
  { q: "Combien de temps faut-il pour qu'un mégot se dégrade (années) ?", a: 12, unit: "ans" },
  { q: "Combien de temps met une bouteille plastique à se dégrader (années) ?", a: 450, unit: "ans" },
  { q: "Combien de sacs plastique sont utilisés par minute dans le monde (millions) ?", a: 2, unit: "millions" },
  { q: "Combien d'arbres faut-il abattre pour un journal quotidien pendant un an ?", a: 24, unit: "arbres" },
  { q: "Combien d'oxygène produit un arbre par jour (litres) ?", a: 100, unit: "litres" },
  { q: "Combien de temps vit une cellule de peau (jours) ?", a: 30, unit: "jours" },
  { q: "Combien de km fait la Grande Barrière de corail ?", a: 2300, unit: "km" },
  { q: "Combien d'espèces vivent dans la Grande Barrière de corail ?", a: 9000, unit: "espèces" },
  { q: "Combien de litres d'eau contient une piscine olympique ?", a: 2500000, unit: "litres" },
  { q: "Combien de terrains de foot représente la superficie de Paris ?", a: 14700, unit: "terrains" },
  { q: "Combien de fois le Titanic était plus long qu'un bus (rapport) ?", a: 27, unit: "bus" },
  { q: "Combien de rivets composaient le Titanic (millions) ?", a: 3, unit: "millions" },
  { q: "Combien de temps le Titanic a-t-il mis à couler (heures) ?", a: 3, unit: "heures" },
  { q: "En quelle année a coulé le Titanic ?", a: 1912, unit: "" },
  { q: "Combien de marches compte la Sagrada Familia (tours) ?", a: 400, unit: "marches" },
  { q: "Depuis combien d'années construit-on la Sagrada Familia ?", a: 143, unit: "ans" },
  { q: "Combien de briques compose la Grande Muraille de Chine (millions) ?", a: 3873000000, unit: "briques" },
  { q: "Combien de blocs de pierre compose la pyramide de Khéops ?", a: 2300000, unit: "blocs" },
  { q: "Combien pèse un bloc moyen de la pyramide de Khéops (tonnes) ?", a: 2, unit: "tonnes" },
];
