const NUMBERS = [
  { q: "En quelle année a été inaugurée la Tour Eiffel ?", a: 1889, unit: "", hint: "Exposition universelle de Paris" },
  { q: "En quelle année Christophe Colomb a-t-il découvert l'Amérique ?", a: 1492, unit: "", hint: "Les rois catholiques d'Espagne l'ont financé" },
  { q: "En quelle année la Révolution française a-t-elle commencé ?", a: 1789, unit: "", hint: "Prise de la Bastille" },
  { q: "En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?", a: 1969, unit: "", hint: "Mission Apollo 11" },
  { q: "En quelle année le mur de Berlin est-il tombé ?", a: 1989, unit: "", hint: "Fin de la guerre froide" },
  { q: "En quelle année Napoléon a-t-il été exilé à Sainte-Hélène ?", a: 1815, unit: "", hint: "Après Waterloo" },
  { q: "En quelle année Jules César a-t-il été assassiné ?", a: -44, unit: "", hint: "Aux ides de mars" },
  { q: "En quelle année a été signé le traité de Versailles ?", a: 1919, unit: "", hint: "Fin de la Première Guerre mondiale" },
  { q: "En quelle année Gutenberg a-t-il inventé l'imprimerie à caractères mobiles ?", a: 1450, unit: "", hint: "Vers le milieu du 15e siècle" },
  { q: "En quelle année la France a-t-elle aboli la peine de mort ?", a: 1981, unit: "", hint: "Sous le garde des sceaux Badinter" },
  { q: "En quelle année l'iPhone a-t-il été présenté pour la première fois ?", a: 2007, unit: "", hint: "Steve Jobs sur scène" },
  { q: "En quelle année Facebook a-t-il été fondé ?", a: 2004, unit: "", hint: "Dans un dortoir de Harvard" },
  { q: "En quelle année la Seconde Guerre mondiale a-t-elle pris fin ?", a: 1945, unit: "", hint: "Capitulation de l'Allemagne puis du Japon" },
  { q: "En quelle année l'Union soviétique s'est-elle dissoute ?", a: 1991, unit: "", hint: "Fin de la guerre froide" },
  { q: "En quelle année Christophe Colomb est-il né ?", a: 1451, unit: "", hint: "À Gênes, Italie" },
  { q: "En quelle année a été fondée la ville de Rome selon la légende ?", a: -753, unit: "", hint: "Par Romulus" },
  { q: "En quelle année a débuté la Première Guerre mondiale ?", a: 1914, unit: "", hint: "Assassinat de François-Ferdinand" },
  { q: "En quelle année a eu lieu le premier vol des frères Wright ?", a: 1903, unit: "", hint: "À Kitty Hawk, Caroline du Nord" },
  { q: "En quelle année Netflix a-t-il lancé son service de streaming ?", a: 2007, unit: "", hint: "Avant ça, c'était des DVD par courrier" },
  { q: "En quelle année l'accord de Paris sur le climat a-t-il été signé ?", a: 2015, unit: "", hint: "COP21" },
  { q: "Quelle est la hauteur de la Tour Eiffel en mètres (avec antenne) ?", a: 330, unit: "m", hint: "Plus haute que la Statue de la Liberté (93m)" },
  { q: "Quelle est la longueur du Nil en km ?", a: 6650, unit: "km", hint: "Le plus long fleuve du monde" },
  { q: "Quelle est la profondeur maximale de la fosse des Mariannes en mètres ?", a: 11000, unit: "m", hint: "Plus profond que l'Everest n'est haut" },
  { q: "Quelle est la distance de la Terre à la Lune en km ?", a: 384400, unit: "km", hint: "En moyenne, varie selon l'orbite" },
  { q: "Quelle est la longueur de la Grande Muraille de Chine en km ?", a: 21196, unit: "km", hint: "Avec toutes ses sections" },
  { q: "Quelle est la hauteur du Mont Everest en mètres ?", a: 8849, unit: "m", hint: "Le toit du monde" },
  { q: "Quelle est la superficie de la France métropolitaine en km² ?", a: 551000, unit: "km²", hint: "Environ la moitié de l'Alaska" },
  { q: "Quelle est la longueur de l'Amazone en km ?", a: 6400, unit: "km", hint: "Traverse l'Amérique du Sud" },
  { q: "Quelle est la distance Terre-Soleil en millions de km ?", a: 150, unit: "millions km", hint: "1 unité astronomique" },
  { q: "Quelle est la vitesse de la lumière en km/s ?", a: 300000, unit: "km/s", hint: "Environ 3×10⁸ m/s" },
  { q: "Quelle est la longueur du Tunnel sous la Manche en km ?", a: 50, unit: "km", hint: "Relie Folkestone à Coquelles" },
  { q: "Quelle est la hauteur de la Statue de la Liberté en mètres (avec socle) ?", a: 93, unit: "m", hint: "Cadeau de la France aux États-Unis" },
  { q: "Quelle est la superficie du Brésil en millions de km² ?", a: 8515767, unit: "km²", hint: "5e plus grand pays du monde" },
  { q: "Quelle est la longueur du Canal de Suez en km ?", a: 193, unit: "km", hint: "Relie la Méditerranée à la mer Rouge" },
  { q: "Quelle est la hauteur de la Burj Khalifa à Dubaï en mètres ?", a: 828, unit: "m", hint: "Plus haute tour du monde" },
  { q: "Quelle est la population mondiale approximative en 2024 (en milliards) ?", a: 8, unit: "milliards", hint: "Ça double tous les ~60 ans environ" },
  { q: "Quelle est la population de la France en millions d'habitants ?", a: 68, unit: "millions", hint: "Environ 5e en Europe" },
  { q: "Quelle est la population de la Chine en milliards ?", a: 1400000000, unit: "habitants", hint: "Légèrement dépassée par l'Inde en 2023" },
  { q: "Quelle est la population de Paris intra-muros en millions ?", a: 2200000, unit: "habitants", hint: "Grande couronne incluse : 12 millions" },
  { q: "Combien de pays composent l'Union européenne ?", a: 27, unit: "pays", hint: "Après le Brexit en 2020" },
  { q: "Combien de pays sont membres de l'ONU ?", a: 193, unit: "pays", hint: "Fondée en 1945 avec 51 membres" },
  { q: "Combien de fois Pelé a-t-il remporté la Coupe du Monde ?", a: 3, unit: "fois", hint: "1958, 1962, 1970" },
  { q: "Combien de Grand Chelem Rafael Nadal a-t-il remportés ?", a: 22, unit: "titres", hint: "Record avec Djokovic" },
  { q: "Combien de médailles d'or Michael Phelps a-t-il remportées aux JO ?", a: 23, unit: "médailles d'or", hint: "Plus grand olympien de l'histoire" },
  { q: "En quelle année la France a-t-elle remporté sa première Coupe du Monde de football ?", a: 1998, unit: "", hint: "À domicile, 3-0 contre le Brésil" },
  { q: "Quel est le record du monde du 100m masculin en centièmes de seconde ?", a: 958, unit: "s (9,58)", hint: "Usain Bolt en 2009 à Berlin" },
  { q: "Combien de fois le Real Madrid a-t-il remporté la Ligue des Champions ?", a: 15, unit: "fois", hint: "Record absolu" },
  { q: "En quelle année les premiers Jeux Olympiques modernes ont-ils eu lieu ?", a: 1896, unit: "", hint: "À Athènes" },
  { q: "Combien de joueurs composent une équipe de football sur le terrain ?", a: 11, unit: "joueurs", hint: "Idem au rugby à XV" },
  { q: "Quel est le record du monde du marathon en minutes ?", a: 120, unit: "min (2h00'35)", hint: "Kelvin Kiptum en 2023" },
  { q: "Combien d'os compte le corps humain adulte ?", a: 206, unit: "os", hint: "Plus que les bébés (270 à la naissance)" },
  { q: "Combien de chromosomes possède un être humain ?", a: 46, unit: "chromosomes", hint: "23 paires" },
  { q: "Quelle est la température du noyau de la Terre en degrés Celsius ?", a: 5500, unit: "°C", hint: "Aussi chaud que la surface du Soleil" },
  { q: "Combien de dents possède un adulte avec ses dents de sagesse ?", a: 32, unit: "dents", hint: "Sans sagesse : 28" },
  { q: "Quelle est la température d'ébullition de l'eau à pression normale ?", a: 100, unit: "°C", hint: "Moins en altitude" },
  { q: "Combien de planètes compte le système solaire ?", a: 8, unit: "planètes", hint: "Pluton déclassée en 2006" },
  { q: "Quelle est la durée d'une révolution de la Terre autour du Soleil en jours ?", a: 365, unit: "jours", hint: "365,25 exactement d'où les années bissextiles" },
  { q: "Combien d'éléments chimiques compte le tableau périodique ?", a: 118, unit: "éléments", hint: "Jusqu'à l'oganesson (Og)" },
  { q: "Quelle est la valeur approximative du nombre Pi (3 premières décimales) ?", a: 3141, unit: "(×1000)", hint: "3,141..." },
  { q: "Combien de litres de sang le cœur pompe-t-il par jour ?", a: 7200, unit: "litres", hint: "Environ 5L/min × 1440 minutes" },
  { q: "En quelle année a été peinte la Joconde par Léonard de Vinci ?", a: 1503, unit: "", hint: "Début du 16e siècle" },
  { q: "Combien de livres Harry Potter compte la saga principale ?", a: 7, unit: "livres", hint: "J.K. Rowling" },
  { q: "En quelle année a été fondée la ville de Paris (Lutèce) selon les historiens ?", a: -250, unit: "", hint: "Les Parisii, tribu gauloise" },
  { q: "Combien de marches compte la Tour Eiffel jusqu'au 2e étage ?", a: 674, unit: "marches", hint: "Accès piéton uniquement jusqu'au 2e" },
  { q: "Quelle est la longueur du Mississippi en km ?", a: 3730, unit: "km", hint: "Plus long fleuve des États-Unis" },
  { q: "Combien de tableaux Vincent van Gogh a-t-il peints au total ?", a: 900, unit: "tableaux", hint: "En seulement 10 ans de carrière" },
  { q: "En quelle année a été créé YouTube ?", a: 2005, unit: "", hint: "Racheté par Google l'année suivante" },
  { q: "Combien de pays partagent une frontière avec la France métropolitaine ?", a: 8, unit: "pays", hint: "Espagne, Andorre, Monaco, Italie, Suisse, Luxembourg, Allemagne, Belgique" },
  { q: "Quel est le numéro atomique de l'or ?", a: 79, unit: "", hint: "Symbole Au" },
  { q: "Combien de secondes y a-t-il dans une heure ?", a: 3600, unit: "secondes", hint: "60 × 60" },
  { q: "Combien de kilomètres de routes y a-t-il en France ?", a: 1000000, unit: "km", hint: "Le réseau routier le plus dense d'Europe" },
  { q: "En quelle année a été créé le réseau social Twitter ?", a: 2006, unit: "", hint: "Fondé par Jack Dorsey" },
  { q: "Quelle est la vitesse maximale d'un guépard en km/h ?", a: 120, unit: "km/h", hint: "L'animal terrestre le plus rapide" },
  { q: "Combien d'étages compte l'Empire State Building ?", a: 102, unit: "étages", hint: "New York, terminé en 1931" },
  { q: "En quelle année Titanic a-t-il coulé ?", a: 1912, unit: "", hint: "Lors de son voyage inaugural" },
  { q: "Combien de notes y a-t-il dans une gamme musicale occidentale ?", a: 7, unit: "notes", hint: "Do Ré Mi Fa Sol La Si" },
  { q: "Quelle est la superficie de la Russie en millions de km² ?", a: 17, unit: "millions km²", hint: "Plus grand pays du monde" },
  { q: "En quelle année Minecraft a-t-il été officiellement lancé ?", a: 2011, unit: "", hint: "Créé par Markus Persson (Notch)" },
  { q: "Combien de Grammy Awards Beyoncé a-t-elle remportés (record absolu, 2024) ?", a: 32, unit: "Grammy", hint: "Record absolu tous artistes confondus" },
  { q: "En quelle année Airbus A380 a-t-il effectué son premier vol commercial ?", a: 2007, unit: "", hint: "Le plus grand avion de ligne du monde" },
  { q: "En quelle année Zinédine Zidane a-t-il donné son coup de tête lors de la finale du Mondial ?", a: 2006, unit: "", hint: "Finale France-Italie à Berlin" },
  { q: "Combien de titres de champion du monde de F1 Lewis Hamilton a-t-il remportés ?", a: 7, unit: "titres", hint: "Record absolu partagé avec Schumacher" },
  { q: "En quelle année Usain Bolt a-t-il établi son record du monde du 100m (9s58) ?", a: 2009, unit: "", hint: "Championnats du monde à Berlin" },
  { q: "Combien de fois la France a-t-elle remporté la Coupe Davis ?", a: 6, unit: "fois", hint: "Notamment 2017 et 2023" },
  { q: "Quel est le record de buts de Ronaldo en une saison de Liga ?", a: 50, unit: "buts", hint: "Saison 2011-2012 avec le Real Madrid" },
  { q: "Combien de mètres mesure un terrain de football officiel (longueur max) ?", a: 105, unit: "m", hint: "Largeur : 68m maximum" },
  { q: "En quelle année le PSG a-t-il été fondé ?", a: 1970, unit: "", hint: "Fusion de deux clubs parisiens" },
  { q: "Combien de points rapporte un essai au rugby à XV ?", a: 5, unit: "points", hint: "Plus la transformation : 7 au total" },
  { q: "Combien de sets faut-il gagner pour remporter une finale de Wimbledon messieurs ?", a: 3, unit: "sets", hint: "Format en 5 sets, 3 gagnants" },
  { q: "En quelle année Michael Jordan a-t-il remporté son 1er titre NBA ?", a: 1991, unit: "", hint: "Avec les Chicago Bulls" },
  { q: "Combien de km fait le Tour de France en moyenne ?", a: 3400, unit: "km", hint: "Varie chaque année, autour de 3 000-3 500" },
  { q: "En quelle année le premier iPhone a-t-il été commercialisé ?", a: 2007, unit: "", hint: "Présenté par Steve Jobs en janvier" },
  { q: "Combien de Mo fait un Go ?", a: 1024, unit: "Mo", hint: "En informatique binaire" },
  { q: "Quel est le numéro atomique du carbone ?", a: 6, unit: "", hint: "Base de toute vie organique" },
  { q: "En quelle année le génome humain a-t-il été entièrement séquencé ?", a: 2003, unit: "", hint: "Projet Génome Humain" },
  { q: "Combien de satellites naturels possède Mars ?", a: 2, unit: "lunes", hint: "Phobos et Déimos" },
  { q: "Quelle est la température moyenne à la surface de Mars en °C ?", a: -60, unit: "°C", hint: "Entre -125°C et +20°C selon la saison" },
  { q: "En quelle année le premier ordinateur personnel grand public (Apple II) est-il sorti ?", a: 1977, unit: "", hint: "Fondateurs : Steve Jobs et Steve Wozniak" },
  { q: "Combien de régions administratives compte la France métropolitaine ?", a: 13, unit: "régions", hint: "Depuis la réforme de 2016" },
  { q: "Quelle est la longueur des côtes françaises métropolitaines en km ?", a: 5800, unit: "km", hint: "Atlantique + Méditerranée + Manche" },
  { q: "Quelle est la superficie de l'Antarctique en millions de km² ?", a: 14, unit: "millions km²", hint: "Couvert à 98% de glace" },
  { q: "À quelle altitude se trouve le Col du Mont-Blanc (tunnel routier) ?", a: 1381, unit: "m", hint: "L'entrée côté France à Chamonix" },
  { q: "Combien de départements compte la France (métropole + outre-mer) ?", a: 101, unit: "départements", hint: "95 métropolitains + 6 d'outre-mer" },
  { q: "En quelle année la Déclaration des droits de l'homme et du citoyen a-t-elle été adoptée ?", a: 1789, unit: "", hint: "Même année que la Révolution" },
  { q: "Combien d'années a duré le règne de Louis XIV ?", a: 72, unit: "ans", hint: "Plus long règne de l'histoire de France" },
  { q: "En quelle année l'Allemagne a-t-elle été réunifiée ?", a: 1990, unit: "", hint: "Un an après la chute du Mur de Berlin" },
  { q: "Combien d'États américains composent les États-Unis ?", a: 50, unit: "États", hint: "Hawaii et Alaska ont rejoint en 1959" },
  { q: "En quelle année l'Algérie a-t-elle obtenu son indépendance ?", a: 1962, unit: "", hint: "Accords d'Évian" },
  { q: "En quelle année Napoléon est-il né ?", a: 1769, unit: "", hint: "À Ajaccio, en Corse" },
  { q: "Combien de saisons compte la série Game of Thrones ?", a: 8, unit: "saisons", hint: "La 8ème a été très controversée" },
  { q: "En quelle année est sorti le film Avatar de James Cameron ?", a: 2009, unit: "", hint: "Film le plus rentable de l'histoire (longtemps)" },
  { q: "Combien de films compte la saga Star Wars (films principaux) ?", a: 9, unit: "films", hint: "Sans les spin-offs" },
  { q: "Combien de caractères maximum permettait Twitter à l'origine ?", a: 140, unit: "caractères", hint: "Doublé à 280 en 2017" },
  { q: "En quelle année Spotify a-t-il été lancé ?", a: 2008, unit: "", hint: "Fondé en Suède par Daniel Ek" },
  { q: "Combien d'albums studio les Beatles ont-ils enregistrés ?", a: 13, unit: "albums", hint: "De Please Please Me à Let It Be" },
  { q: "En quelle année le film Titanic de James Cameron est-il sorti ?", a: 1997, unit: "", hint: "11 Oscars dont meilleur film" },
  { q: "Combien de langues sont actuellement reconnues comme langues officielles à l'ONU ?", a: 6, unit: "langues", hint: "Anglais, français, arabe, chinois, russe, espagnol" },
  { q: "Combien de millions d'abonnés possède la chaîne YouTube la plus suivie (T-Series) ?", a: 270, unit: "millions", hint: "Chaîne de Bollywood indienne" },,
  { q: "En quelle année Michael Jackson est-il décédé ?", a: 2009, unit: "" },
  { q: "Combien de kilomètres sépare Paris de New York à vol d'oiseau ?", a: 5837, unit: "km" },
  { q: "Combien y a-t-il de touches sur un piano standard ?", a: 88, unit: "touches" },
  { q: "En quelle année la Game Boy est-elle sortie en Europe ?", a: 1990, unit: "" },
  { q: "Combien de joueurs composent une équipe de rugby à XV sur le terrain ?", a: 15, unit: "joueurs" },
  { q: "Combien de départements compte la France (métropole + outre-mer) ?", a: 101, unit: "départements" },
  { q: "En quelle année a eu lieu la catastrophe de Tchernobyl ?", a: 1986, unit: "" },
  { q: "Combien de dents possède un adulte (dents de sagesse comprises) ?", a: 32, unit: "dents" },
  { q: "Quelle est la profondeur maximale de la fosse des Mariannes en mètres ?", a: 10984, unit: "m" },
  { q: "Combien d'étoiles figurent sur le drapeau américain ?", a: 50, unit: "étoiles" },
  { q: "En quelle année le premier iPhone est-il sorti ?", a: 2007, unit: "" },
  { q: "Combien de cases y a-t-il sur un échiquier ?", a: 64, unit: "cases" },
  { q: "Combien de minutes dure un match de football (temps réglementaire) ?", a: 90, unit: "minutes" },
  { q: "En quelle année Zinédine Zidane a-t-il mis son coup de boule à Materazzi ?", a: 2006, unit: "" },
  { q: "Combien de pays partagent une frontière terrestre avec la France métropolitaine ?", a: 8, unit: "pays" },
  { q: "Quelle est la vitesse maximale d'un guépard en km/h ?", a: 110, unit: "km/h" },
  { q: "Combien y a-t-il de zéros dans un milliard ?", a: 9, unit: "zéros" },
  { q: "En quelle année Facebook a-t-il été créé ?", a: 2004, unit: "" },
  { q: "Combien de côtés a un hendécagone ?", a: 11, unit: "côtés" },
  { q: "Combien de temps met la lumière du Soleil pour atteindre la Terre en minutes ?", a: 8, unit: "minutes" },
  { q: "En quelle année la Coupe du monde a-t-elle eu lieu au Qatar ?", a: 2022, unit: "" },
  { q: "Combien de films Harry Potter existe-t-il ?", a: 8, unit: "films" },
  { q: "Combien de saisons compte la série Game of Thrones ?", a: 8, unit: "saisons" },
  { q: "En quelle année est sorti le premier film Star Wars ?", a: 1977, unit: "" },
  { q: "Combien pèse un ballon de football en grammes (environ) ?", a: 430, unit: "g" },
  { q: "Combien de Grammy Awards Beyoncé a-t-elle remportés (record) ?", a: 32, unit: "Grammys" },
  { q: "En quelle année Nirvana a-t-il sorti Nevermind ?", a: 1991, unit: "" },
  { q: "Combien de cordes possède une guitare classique ?", a: 6, unit: "cordes" },
  { q: "Combien de albums studio a sorti Jul (environ, fin 2024) ?", a: 34, unit: "albums" },
  { q: "En quelle année Stromae a-t-il sorti Alors on danse ?", a: 2009, unit: "" },
  { q: "Combien de spectateurs peut accueillir le Stade de France ?", a: 80698, unit: "places" },
  { q: "Combien de km fait le tour de la Terre à l'équateur ?", a: 40075, unit: "km" },
  { q: "Combien y a-t-il de secondes dans une journée ?", a: 86400, unit: "secondes" },
  { q: "En quelle année est né Kylian Mbappé ?", a: 1998, unit: "" },
  { q: "Combien de Ballons d'Or Lionel Messi a-t-il remportés ?", a: 8, unit: "Ballons d'Or" },
  { q: "Combien de titres de champion du monde de F1 a Lewis Hamilton ?", a: 7, unit: "titres" },
  { q: "Combien de km/h fait la vitesse du son (environ) ?", a: 1224, unit: "km/h" },
  { q: "En quelle année la Réunion est-elle devenue un département français ?", a: 1946, unit: "" },
  { q: "Combien d'épisodes compte la série Friends ?", a: 236, unit: "épisodes" },
  { q: "Combien de lettres compte l'alphabet grec ?", a: 24, unit: "lettres" },
  { q: "En quelle année a été inventé le World Wide Web ?", a: 1989, unit: "" },
  { q: "Combien de communes compte la France (environ) ?", a: 34955, unit: "communes" },
  { q: "Quelle est la hauteur du Mont Blanc en mètres ?", a: 4806, unit: "m" },
  { q: "Combien de calories dans un Big Mac ?", a: 550, unit: "kcal" },
  { q: "En quelle année GTA V est-il sorti ?", a: 2013, unit: "" },
  { q: "Combien d'or (en tonnes) détient la Banque de France (environ) ?", a: 2436, unit: "tonnes" },
  { q: "Combien de marches pour monter au sommet de la tour Eiffel ?", a: 1665, unit: "marches" },
  { q: "Combien de joueurs simultanés maximum dans une partie de Fortnite Battle Royale ?", a: 100, unit: "joueurs" },
  { q: "En quelle année Daft Punk s'est-il séparé ?", a: 2021, unit: "" },
  { q: "Combien de pattes possède une araignée ?", a: 8, unit: "pattes" },
];
